### ISSUE TITLE
[Minor Bug] Using CPS more than once on a player throws NPE

### ISSUE THREAD

**Issue by Jadiction** [Qballl/StaffPlus#112]
Title says it all, using the CPS tool more than once (before the first one finishes) throws a NullPointerException. 

Staff+ version: 3.2.9 (Although /ver shows 3.3.0)
Using the latest paper version for MC 1.14.4

Console error:
```29.09 20:09:22 [Server] WARN [StaffPlus] Task #19332 for StaffPlus v3.3.0 generated an exception
29.09 20:09:22 [Server] INFO java.lang.NullPointerException: null
29.09 20:09:22 [Server] INFO at net.shortninja.staffplus.player.attribute.mode.handler.CpsHandler.stopTest(CpsHandler.java:47) ~[?:?]
29.09 20:09:22 [Server] INFO at net.shortninja.staffplus.player.attribute.mode.handler.CpsHandler$1.run(CpsHandler.java:38) ~[?:?]
29.09 20:09:22 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:09:22 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:09:22 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:09:22 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:09:22 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:09:22 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:09:22 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]```

**Comment by Qballl** [comment]
Think I have this fixed not gonna close it yes though

**Comment by Jadiction** [comment]
Haven't had this issue happen since the update(s), going to close now.
