### ISSUE TITLE
[Minor Bug] Moving glass pane in the GUI Hub throws error

### ISSUE THREAD

**Issue by Jadiction** [Qballl/StaffPlus#113]
Moving the glass pane in the GUI Hub on both the left and right sides to anywhere throws an error. 

Staff+ version: 3.2.9 (Although /ver shows 3.3.0)
Using the latest paper version for MC 1.14.4

Console error:
```29.09 20:11:59 [Server] ERROR Could not pass event InventoryClickEvent to StaffPlus v3.3.0
29.09 20:11:59 [Server] INFO java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.STAINED_GLASS_PANE
29.09 20:11:59 [Server] INFO at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_212]
29.09 20:11:59 [Server] INFO at org.bukkit.Material.valueOf(Material.java:83) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.shortninja.staffplus.player.attribute.gui.ColorGui.glassItem(ColorGui.java:50) ~[?:?]
29.09 20:11:59 [Server] INFO at net.shortninja.staffplus.player.attribute.gui.ColorGui.<init>(ColorGui.java:38) ~[?:?]
29.09 20:11:59 [Server] INFO at net.shortninja.staffplus.player.attribute.gui.AbstractGui$1.click(AbstractGui.java:57) ~[?:?]
29.09 20:11:59 [Server] INFO at net.shortninja.staffplus.server.listener.InventoryClick.onClick(InventoryClick.java:47) ~[?:?]
29.09 20:11:59 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor333.execute(Unknown Source) ~[?:?]
29.09 20:11:59 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1135) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-200]
29.09 20:11:59 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]```

**Comment by Azoraqua** [comment]
It has to do with the code not being made for Bukkit 1.14.4. As the API has changed and removed the 'STAINED_GLASS_PANE' field which was present in an earlier version of the Bukkit API.

We'll take a look into (gracefully) falling back to a suitable option.

**Comment by Qballl** [comment]
Fixed it. I had a simple but flawed system for checking the version it checked the string now I check it as int and is forward compatible
