### ISSUE TITLE
Default configuration: Error velocity

### ISSUE THREAD

**Issue by Neewen** [Qballl/StaffPlus#144]
The video:
https://youtu.be/ij66PEQgRKU

The Error:
```
[21:21:02 WARN]: Excessive velocity set detected: tried to set velocity of entity #84 to (4.8879915053001595,1.0523621836642265,-0.008536890941497047).
[21:21:02 WARN]: java.lang.Exception: Stack trace
[21:21:02 WARN]:        at java.lang.Thread.dumpStack(Thread.java:1336)
[21:21:02 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.entity.CraftEntity.setVelocity(CraftEntity.java:210)
[21:21:02 WARN]:        at net.shortninja.staffplus.player.attribute.mode.handler.GadgetHandler.onCompass(GadgetHandler.java:82)
[21:21:02 WARN]:        at net.shortninja.staffplus.server.listener.player.PlayerInteract.handleInteraction(PlayerInteract.java:112)
[21:21:02 WARN]:        at net.shortninja.staffplus.server.listener.player.PlayerInteract.onInteract(PlayerInteract.java:51)
[21:21:02 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor88.execute(Unknown Source)
[21:21:02 WARN]:        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[21:21:02 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[21:21:02 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:21:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[21:21:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[21:21:02 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231)
[21:21:02 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198)
[21:21:02 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194)
[21:21:02 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:946)
[21:21:02 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:27)
[21:21:02 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5)
[21:21:02 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[21:21:02 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:21:02 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:21:02 WARN]:        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[21:21:02 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786)
[21:21:02 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403)
[21:21:02 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723)
[21:21:02 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622)
[21:21:02 WARN]:        at java.lang.Thread.run(Thread.java:748)
```
Versions:
![image](https://user-images.githubusercontent.com/62424178/80411426-7c663380-88cc-11ea-8067-2409c05e2bb5.png)
![image](https://user-images.githubusercontent.com/62424178/80411448-8425d800-88cc-11ea-85cc-777a6d552729.png)
![image](https://user-images.githubusercontent.com/62424178/80411478-8e47d680-88cc-11ea-93ad-f2cd0f69b376.png)

**Comment by Qballl** [comment]
Fixed on dev version

**Comment by Neewen** [comment]
Hello, can I get the update with the bug fix?

**Comment by Qballl** [comment]
Check the pins in the discord channel
