### ISSUE TITLE
Error Starting Up

### ISSUE THREAD

**Issue by Tomigames** [Qballl/StaffPlus#148]
[08:10:36] [Server thread/INFO]: [StaffPlus] Enabling StaffPlus v3.3.2.2
[08:10:36] [Server thread/INFO]: [APIManager] API class 'org.inventivetalent.packetlistener.PacketListenerAPI' is not yet initialized. Creating new instance.
[08:10:36] [Server thread/INFO]: [ReflectionHelper] I am loaded from package org.inventivetalent.packetlistener.reflection.minecraft
[08:10:36] [Server thread/INFO]: [ReflectionHelper] Version is v1_14_R1 (11401)
[08:10:36] [Server thread/INFO]: [PacketListenerAPI] Using INChannel
[08:10:36] [Server thread/WARN]: java.lang.NoSuchFieldException: list
[08:10:36] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[08:10:36] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.channel.ChannelAbstract.addServerChannel(ChannelAbstract.java:69)
[08:10:36] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.ChannelInjector.addServerChannel(ChannelInjector.java:55)
[08:10:36] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:32)
[08:10:36] [Server thread/WARN]: 	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:46)
[08:10:36] [Server thread/WARN]: 	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:117)
[08:10:36] [Server thread/WARN]: 	at net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:134)
[08:10:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:10:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[08:10:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[08:10:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[08:10:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[08:10:36] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[08:10:36] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[08:10:36] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[08:10:36] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by Azoraqua** [comment]
Not an issue caused by StaffPlus.
