### ISSUE TITLE
Failed to get resource info

### ISSUE THREAD

**Issue by srnyx** [Qballl/StaffPlus#149]
Paper-Spigot 1.14.4, plugin version 3.3.2.3

`[15:23:54] [Craft Scheduler Thread - 19/WARN]: [StaffPlus] Failed to get resource info from spiget.org
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_242]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_242]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_242]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_242]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_242]
	at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_242]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666) ~[?:1.8.0_242]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[?:1.8.0_242]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_242]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_242]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_242]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0_242]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_242]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.8.0_242]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[?:1.8.0_242]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[?:1.8.0_242]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_242]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570) ~[?:1.8.0_242]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_242]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_242]
	at org.inventivetalent.update.spiget.SpigetUpdateAbstract$1.run(SpigetUpdateAbstract.java:92) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[paper-1.14.4.jar:git-Paper-219]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[paper-1.14.4.jar:git-Paper-219]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.14.4.jar:git-Paper-219]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

Full latest.log: https://pastebin.com/2caQtJgb

**Comment by Azoraqua** [comment]
It means it cannot connect with SpiGet. Shouldn't be too important, it just means the auto-updater doesn't work. Besides, it's not exactly from StaffPlus itself and therefore I'll close this issue.
