### ISSUE TITLE
Its not working - console log

### ISSUE THREAD

**Issue by TheGamerKid-YT** [Qballl/StaffPlus#159]
Could not pass event PlayerMoveEvent to AcceptTheRules v2.5

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1011) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.PacketPlayInFlying.a(SourceFile:122) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:86) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.PlayerConnectionUtils$$Lambda$4549.00000000440CA540.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2922.000000001D8F7780.run(Unknown Source) ~[?:?]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NullPointerException

at net.md_5.bungee.api.ChatColor.translateAlternateColorCodes(ChatColor.java:216) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

at me.morelaid.AcceptTheRules.Handler.Files.Rules.getVersion(Rules.java:26) ~[?:?]

at me.morelaid.AcceptTheRules.Handler.FunctionHandler.hasAccepted(FunctionHandler.java:303) ~[?:?]

at me.morelaid.AcceptTheRules.Event.Events.onPlayerMove(Events.java:74) ~[?:?]

at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-75a2fb8]

... 20 more

**Comment by Azoraqua** [comment]
It doesn't have to do with StaffPlus at all and therefore it's closed. 
May I suggest to look at this page: https://www.spigotmc.org/resources/accept-the-rules-1-9-1-16-x-forces-players-to-read-and-accept-your-rules.53775/
