### ISSUE TITLE
Problems with staffplus

### ISSUE THREAD

**Issue by jCripton** [Qballl/StaffPlus#16]
I use latest version and when i type /staff in console there is 
[22:19:18 INFO]: Criptos issued server command: /staff
[22:19:18 INFO]: Unknown command.
[22:19:18 INFO]: Unknown command.

**Comment by Qballl** [comment]
What server version?

**Comment by jCripton** [comment]
1.7.10

**Comment by jCripton** [comment]
but the plugin's work but in console spam this

**Comment by jCripton** [comment]
hey ?

**Comment by Qballl** [comment]
Umm can you provide any more information?

**Comment by jCripton** [comment]
Unknown command in console +                                                                                                    [18:19:04] [Netty IO #3/WARN]: [PacketListenerAPI] An exception occured while trying to execute 'onSend' in plugin StaffPlus: null
[18:19:04] [Netty IO #3/WARN]: java.lang.NullPointerException
[18:19:04] [Netty IO #3/WARN]: 	at net.shortninja.staffplus.server.PacketModifier.isVanished(PacketModifier.java:173)
[18:19:04] [Netty IO #3/WARN]: 	at net.shortninja.staffplus.server.PacketModifier.handleClientSound(PacketModifier.java:81)
[18:19:04] [Netty IO #3/WARN]: 	at net.shortninja.staffplus.server.PacketModifier.access$000(PacketModifier.java:20)
[18:19:04] [Netty IO #3/WARN]: 	at net.shortninja.staffplus.server.PacketModifier$1.onSend(PacketModifier.java:42)
[18:19:04] [Netty IO #3/WARN]: 	at org.inventivetalent.packetlistener.handler.PacketHandler.notifyHandlers(PacketHandler.java:81)
[18:19:04] [Netty IO #3/WARN]: 	at org.inventivetalent.packetlistener.PacketListenerAPI.onPacketSend(PacketListenerAPI.java:118)
[18:19:04] [Netty IO #3/WARN]: 	at org.inventivetalent.packetlistener.channel.ChannelAbstract.onPacketSend(ChannelAbstract.java:85)
[18:19:04] [Netty IO #3/WARN]: 	at org.inventivetalent.packetlistener.channel.NMUChannel$ChannelHandler.write(NMUChannel.java:140)
[18:19:04] [Netty IO #3/WARN]: 	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
[18:19:04] [Netty IO #3/WARN]: 	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
[18:19:04] [Netty IO #3/WARN]: 	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688)
[18:19:04] [Netty IO #3/WARN]: 	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717)
[18:19:04] [Netty IO #3/WARN]: 	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893)
[18:19:04] [Netty IO #3/WARN]: 	at net.minecraft.util.io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239)
[18:19:04] [Netty IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:310)
[18:19:04] [Netty IO #3/WARN]: 	at net.minecraft.server.v1_7_R4.QueuedProtocolSwitch.run(SourceFile:143)
[18:19:04] [Netty IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:327)
[18:19:04] [Netty IO #3/WARN]: 	at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
[18:19:04] [Netty IO #3/WARN]: 	at net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348)
[18:19:04] [Netty IO #3/WARN]: 	at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
[18:19:04] [Netty IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:19:05] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to StaffPlus v3.2.4.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(CraftEventFactory.java:108) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:554) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:467) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:586) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.EntityLiving.d(EntityLiving.java:1040) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.EntityHuman.d(EntityHuman.java:825) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:684) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.EntityHuman.damageEntity(EntityHuman.java:766) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.EntityPlayer.damageEntity(EntityPlayer.java:465) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.EntityHuman.attack(EntityHuman.java:951) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1207) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:37) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.handle(PacketPlayInUseEntity.java:49) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:789) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:638) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:544) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
Caused by: java.lang.NullPointerException
	at net.shortninja.staffplus.server.listener.entity.EntityDamageByEntity.onDamage(EntityDamageByEntity.java:45) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[PaperSpigot.jar:git-PaperSpigot-1.7.9-R0.2-273-g5811366]
	... 23 more

**Comment by jCripton** [comment]
Version of server is 1.7.10 PaperSpigot

**Comment by pozzzzy** [comment]
Isn't compatible with PaperSpigot afaik.

**Comment by Qballl** [comment]
I think it should support paper I will test personally

**Comment by Qballl** [comment]
Is this still an issue?

**Comment by Qballl** [comment]
No new information in months closing this if you need help just comment on it I will get an email for it still
