### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by GuerreroBit** [Qballl/StaffPlus#162]
Console spam:
`[17:18:39 ERROR]: java.lang.NullPointerException
[17:18:39 WARN]: java.lang.NullPointerException
[17:18:39 WARN]:        at net.minecraft.server.v1_16_R1.PacketDataSerializer.a(PacketDataSerializer.java:203)
[17:18:39 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayOutChat.b(PacketPlayOutChat.java:45)
[17:18:39 WARN]:        at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:42)
[17:18:39 WARN]:        at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:12)
[17:18:39 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
[17:18:39 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:18:39 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[17:18:39 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
[17:18:39 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[17:18:39 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
[17:18:39 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[17:18:39 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:18:39 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[17:18:39 WARN]:        at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:143)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:18:39 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)`
_**[17:18:39 WARN]:        at net.shortninja.staffplus.server.compatibility.AbstractPacketHandler.write(AbstractPacketHandler.java:19)**_
`[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:18:39 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[17:18:39 WARN]:        at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:143)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[17:18:39 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[17:18:39 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[17:18:39 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[17:18:39 WARN]:        at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
[17:18:39 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[17:18:39 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[17:18:39 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[17:18:39 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[17:18:39 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:18:39 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:18:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)`

**Comment by Qballl** [comment]
When does this happen?

**Comment by GuerreroCraft61** [comment]
When using /vanish
(I have essentials and SuperVanish)
