### ISSUE TITLE
Could not pass event PlayerJoinEvent to StaffPlus v3.3.3.0

### ISSUE THREAD

**Issue by C0bra12** [Qballl/StaffPlus#163]
`Could not pass event PlayerJoinEvent to StaffPlus v3.3.3.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:1.12.2-ce4aee7]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:1.12.2-ce4aee7]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:1.12.2-ce4aee7]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:1.12.2-ce4aee7]
at net.minecraft.server.management.PlayerList.playerLoggedIn(PlayerList.java:471) [pl.class:?]
at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:245) [pl.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:259) [NetworkDispatcher.class:1.12.2-ce4aee7]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:70) [NetworkDispatcher.class:1.12.2-ce4aee7]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:204) [NetworkDispatcher$1.class:1.12.2-ce4aee7]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:298) [gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:196) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:923) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:470) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException
at net.shortninja.staffplus.player.attribute.InventorySerializer.shouldLoad(InventorySerializer.java:64) ~[?:?]
at net.shortninja.staffplus.server.listener.player.PlayerJoin.loadInv(PlayerJoin.java:83) ~[?:?]
at net.shortninja.staffplus.server.listener.player.PlayerJoin.onJoin(PlayerJoin.java:69) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor197.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:1.12.2-ce4aee7]
... 15 more`

**Comment by garagepoort** [comment]
@C0bra12 fixed in Staff++. https://www.spigotmc.org/resources/staff.83562/
