### ISSUE TITLE
StaffPlus is compiling against an old Spigot version.

### ISSUE THREAD

**Issue by garagepoort** [Qballl/StaffPlus#165]
Hi,

We saw in the code base the core modules are compiling against on older version of spigot.
At runtime this can lead to problems if we are using a different version of spigot.

Because of the above we discovered the following issue:
Double chests can not be opened on Duty fails with following error. 

```
java.lang.IllegalArgumentException: Invalid inventory size; expected 27 or less
        at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftInventory.setContents(CraftInventory.java:85) ~[patched_1.16.2.jar:git-Tuinity-"158e03c"]
        at net.shortninja.staffplus.server.listener.player.PlayerInteract.onInteract(PlayerInteract.java:64) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor856.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Tuinity-"158e03c"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Tuinity-"158e03c"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Tuinity-"158e03c"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Tuinity-"158e03c"]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[patched_1.16.2.jar:git-Tuinity-"158e03c"]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:492) ~[patched_1.16.2.jar:git-Tuinity-"158e03c"]
```

When debugging the code I noticed a wrong method on the class CraftInventory is triggered. The different method always returned a small chest. Hence the problem with opening double chests.

After some digging I figured out this was due to the difference in versions when compiling staffplus (v1.14) and running on our server (v1.16).
To avoid these problems in the future I suggest releasing and maintaining different versions of the plugin rather than trying to support everything in one codebase.

Also I noticed the language file were wrongly merged.

Anyway I created a pull request which fixes the issue for 1.16.
The pull request is just an example how I fixed it. I am sure you might have a cleaner way of fixing this.

https://github.com/Qballl/StaffPlus/pull/164

**Comment by Qballl** [comment]
Can you explain what's wrong with the lang files?

**Comment by garagepoort** [comment]
> Can you explain what's wrong with the lang files?

Well you fixed it here: https://github.com/Qballl/StaffPlus/pull/166
But in my PR you can see solme of the lang files on master contained the ">>>>>>" from a bad git merge

**Comment by Qballl** [comment]
Oh yea somehow master commit history got deleted and had to do some hacky stuff to get it bad and well look at commit history there is a few named fixing merge issues or something like that. Thanks anyway for the help

**Comment by garagepoort** [comment]
@Qballl I tried your new released version but the bug still remains.
I looked at the latest commits and the spigot version was not updated thus leaving us with the exact same bug.
Can you update the spigot version? You will notice that backwards compatibility can not be guaranteed as old methods are deprecated and no longer working. I still suggest creating different tags for the different version.
