### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EvilSlime** [Qballl/StaffPlus#19]
[06:31:21] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'STAFFPLUS RELOAD' in net.shortninja.staffplus.server.command.cmd.StaffPlusCmd(staffplus)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NullPointerException: permission
at me.lucko.luckperms.bukkit.model.permissible.LPPermissible.hasPermission(LPPermissible.java:123) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
at net.shortninja.staffplus.util.PermissionHandler.has(PermissionHandler.java:43) ~[?:?]
at net.shortninja.staffplus.server.command.cmd.StaffPlusCmd.execute(StaffPlusCmd.java:25) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
... 14 more

**Comment by EvilSlime** [comment]
I had no problems before the update.

**Comment by Qballl** [comment]
Actually looking at this it may even be a luckperms error

**Comment by Qballl** [comment]
Im gonna close this you can still comment here just look under the closed issues
