### ISSUE TITLE
Staff+ dosen't work in 1.16.5

### ISSUE THREAD

**Issue by quentin2160** [Qballl/StaffPlus#190]
```
[StaffPlus] Enabling StaffPlus v3.2.2
[02:47:47] [Server thread/ERROR]: Error occurred while enabling StaffPlus v3.2.2 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.LEGACY_SPAWNER
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_282]
        at org.bukkit.Material.valueOf(Material.java:1) ~[server.jar:3045-Spigot-a25e8ed-115244c]
        at org.bukkit.craftbukkit.v1_16_R3.legacy.CraftLegacy.valueOf(CraftLegacy.java:227) ~[server.jar:3045-Spigot-a25e8ed-115244c]
        at net.shortninja.staffplus.server.data.config.Options.stringToMaterial(Options.java:479) ~[?:?]
        at net.shortninja.staffplus.server.data.config.Options.stringToMaterialList(Options.java:422) ~[?:?]
        at net.shortninja.staffplus.server.data.config.Options.<init>(Options.java:124) ~[?:?]
        at net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:102) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3045-Spigot-a25e8ed-115244c]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[server.jar:3045-Spigot-a25e8ed-115244c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3045-Spigot-a25e8ed-115244c]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:493) ~[server.jar:3045-Spigot-a25e8ed-115244c]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:407) ~[server.jar:3045-Spigot-a25e8ed-115244c]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:555) ~[server.jar:3045-Spigot-a25e8ed-115244c]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[server.jar:3045-Spigot-a25e8ed-115244c]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[server.jar:3045-Spigot-a25e8ed-115244c]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[server.jar:3045-Spigot-a25e8ed-115244c]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

**Comment by Qballl** [comment]
Try updating the plugin you're a few versions out
