### ISSUE TITLE
In 1.16.5 Staff+ doesn't work

### ISSUE THREAD

**Issue by zMawii** [Qballl/StaffPlus#192]
[20:26:08 INFO]: [Staff+] Version protocol set to 'v1_16_R3'.
[20:26:08 WARN]: [StaffPlus] Loaded class at.favre.lib.crypto.bcrypt.BCrypt from UserLogin v2.10.2 which is not a depend, softdepend or loadbefore of this plugin.
[20:26:08 ERROR]: Error occurred while enabling StaffPlus v3.3.5.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'at.favre.lib.crypto.bcrypt.LongPasswordStrategy at.favre.lib.crypto.bcrypt.LongPasswordStrategies.strict()'
        at net.shortninja.staffplus.player.attribute.SecurityHandler.<init>(SecurityHandler.java:33) ~[?:?]
        at net.shortninja.staffplus.StaffPlus.start(StaffPlus.java:206) ~[?:?]
        at net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:145) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-662]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-662]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-662]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-662]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-662]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:592) ~[patched_1.16.5.jar:git-Paper-662]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-662]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-662]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-662]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[20:26:08 INFO]: [StaffPlus] Disabling StaffPlus v3.3.5.0
[20:26:08 INFO]: [Staff+] Staff+ is now disabling!
[20:26:08 ERROR]: Error occurred while disabling StaffPlus v3.3.5.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.shortninja.staffplus.server.hook.HookHandler.disableAll()" because "this.hookHandler" is null
        at net.shortninja.staffplus.StaffPlus.stop(StaffPlus.java:378) ~[?:?]
        at net.shortninja.staffplus.StaffPlus.onDisable(StaffPlus.java:175) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-662]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.5.jar:git-Paper-662]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Paper-662]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.5.jar:git-Paper-662]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-662]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-662]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-662]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:592) ~[patched_1.16.5.jar:git-Paper-662]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-662]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-662]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-662]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Azoraqua** [comment]
Make sure to use the most recent version of StaffPlus. 

Additionally, the auth module is removed.
