### ISSUE TITLE
Cannot find main class `net.shortninja.staffplus.StaffPlus'

### ISSUE THREAD

**Issue by AcevedoDario** [Qballl/StaffPlus#196]
[11:07:55] [Server thread/ERROR] [Minecraft]: Could not load 'plugins/Staff+.jar' in folder 'plugins'
 org.bukkit.plugin.InvalidPluginException: Cannot find main class `net.shortninja.staffplus.StaffPlus'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[PluginClassLoader.class:1bc8635]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[JavaPluginLoader.class:1bc8635]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:330) ~[SimplePluginManager.class:1bc8635]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [SimplePluginManager.class:1bc8635]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:322) [CraftServer.class:1bc8635]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:416) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:321) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:688) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.ClassNotFoundException: Failed to remap class net.shortninja.staffplus.StaffPlus
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:195) ~[PluginClassLoader.class:1bc8635]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[PluginClassLoader.class:1bc8635]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[PluginClassLoader.class:1bc8635]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_282]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_282]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:74) ~[PluginClassLoader.class:1bc8635]
        ... 8 more
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at org.magmafoundation.magma.remapper.remappers.MagmaClassRepo.findClass0(MagmaClassRepo.java:50) ~[Magma-1bc8635-server.jar:1bc8635]
        at net.md_5.specialsource.repo.CachingRepo.findClass(CachingRepo.java:46) ~[SpecialSource-1.8.5.jar:?]
        at org.magmafoundation.magma.remapper.remappers.MagmaInheritanceProvider.findNormalParents(MagmaInheritanceProvider.java:75) ~[Magma-1bc8635-server.jar:1bc8635]
        at org.magmafoundation.magma.remapper.remappers.MagmaInheritanceProvider.fineParents(MagmaInheritanceProvider.java:48) ~[Magma-1bc8635-server.jar:1bc8635]
        at org.magmafoundation.magma.remapper.remappers.MagmaInheritanceProvider.getParents(MagmaInheritanceProvider.java:41) ~[Magma-1bc8635-server.jar:1bc8635]
        at org.magmafoundation.magma.remapper.remappers.MagmaInheritanceProvider.getParents(MagmaInheritanceProvider.java:34) ~[Magma-1bc8635-server.jar:1bc8635]
        at org.magmafoundation.magma.remapper.remappers.MagmaJarMapping.tryClimb(MagmaJarMapping.java:255) ~[Magma-1bc8635-server.jar:1bc8635]
        at org.magmafoundation.magma.remapper.remappers.MagmaJarMapping.tryClimb(MagmaJarMapping.java:262) ~[Magma-1bc8635-server.jar:1bc8635]
        at org.magmafoundation.magma.remapper.remappers.MagmaJarRemapper.mapFieldName(MagmaJarRemapper.java:134) ~[Magma-1bc8635-server.jar:1bc8635]
        at net.md_5.specialsource.CustomRemapper.mapFieldName(CustomRemapper.java:50) ~[SpecialSource-1.8.5.jar:?]
        at org.objectweb.asm.commons.ClassRemapper.visitField(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at org.objectweb.asm.tree.FieldNode.accept(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at org.objectweb.asm.tree.ClassNode.accept(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at org.magmafoundation.magma.remapper.utils.RemappingUtils.remapFindClass(RemappingUtils.java:113) ~[RemappingUtils.class:1bc8635]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:183) ~[PluginClassLoader.class:1bc8635]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[PluginClassLoader.class:1bc8635]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[PluginClassLoader.class:1bc8635]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_282]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_282]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:74) ~[PluginClassLoader.class:1bc8635]
        ... 8 more

**Comment by Qballl** [comment]
What type of server is this IE Paper spigot cb?

**Comment by AcevedoDario** [comment]
Hmmm... It's a Magma one?

**Comment by Qballl** [comment]
Well Imma chalk it up to an issue with magma but there is another issue magma can only run on java 8 and staff+ now needs java 16 due to support of 1.17

**Comment by MissGamerz** [comment]
people need to stop with hybrid servers in production environments

**Comment by Qballl** [comment]
Closing as I dont believe this was an issue with staff+ and there is now a new update so this could also be fixed
