### ISSUE TITLE
Console spam everytime I break a stone block

### ISSUE THREAD

**Issue by smuggufo** [Qballl/StaffPlus#2]
Here is the console
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]

It will keep spamming that as long as a player is breaking stone. It really lags my server

**Comment by Qballl** [comment]
Is there an error after this or before this or is this all it tells you?

**Comment by smuggufo** [comment]
Could not pass event BlockBreakEvent to StaffPlus v3.2.3
org.bukkit.event.EventException: null
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins%20v1.1.0.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:883) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.StackOverflowError
        at java.io.File.<init>(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.RegionFileCache.a(RegionFileCache.java:16) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.RegionFileCache.d(RegionFileCache.java:79) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:62) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:21) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:1) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:336) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:131) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:95) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:193) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:201) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:197) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]

**Comment by Qballl** [comment]
Are you sure your world isn't corrupted at some chunk as the root cause of the error is an IOException

**Comment by smuggufo** [comment]
Im dont think it is. I dont have any problems with the world. Everything works fine except when someone mines stoneblocks anywhere in the world. If it was corrupted how would i go about finding out?

**Comment by Qballl** [comment]
Hmm idk I'm gonna have to get a second opinion on this error. I noticed that there is no line that mentions staffplus so does the original error come at random without this error?

**Comment by smuggufo** [comment]
I never even noticed the first error before today, The "at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]" error i posted all those lines are from breaking one stone block in survival. Usually my console is to spammed with it to scroll all the way up

**Comment by smuggufo** [comment]
Also is there any way to stop it from saying in chat when a player mines stone?

**Comment by Qballl** [comment]
I can disable the vein checker for now until I properly fix otherwise this could crash your server.

**Comment by Qballl** [comment]
https://www.dropbox.com/s/rxjxyhj6j4ori8z/Staff%2B.jar?dl=0 Here is a version with this disabled so we wont crash servers now https://www.dropbox.com/s/rxjxyhj6j4ori8z/Staff%2B.jar?dl=0

**Comment by smuggufo** [comment]
Thank you, I'll install that now and see what happens

**Comment by smuggufo** [comment]
That actually really helped. The only problem now is it spams the staffs chat everytime a player mines stone which is quite alot. Any way to remove that? Its not very useful since its just stone

**Comment by Qballl** [comment]
Ill remove the feature till i fix it when I get a chance

**Comment by Qballl** [comment]
Alright redownload from the dropbox link

**Comment by smuggufo** [comment]
Thank you good sir! Thank you for all the help, you do have an amazing plugin!

**Comment by Qballl** [comment]
Here please try this https://github.com/Qballl/StaffPlus/releases/tag/3.2.4 I believe that should fix the lag that was being caused by a recursive method call techy stuff but you noticed the lag and reported it so I can not thank you enough

**Comment by smuggufo** [comment]
Im only seeing the source code not the .jar but you're welcome!

**Comment by Qballl** [comment]
Hmm let me look at this

**Comment by Qballl** [comment]
Fixed it

**Comment by smuggufo** [comment]
The console spam is back and it seems worse.
at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:91) ~[?:?]at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:91) ~[?:?]at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:91) ~[?:?]at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:91) ~[?:?

**Comment by smuggufo** [comment]
[20:12:36][Spigot Watchdog Thread/ERROR]: net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:91)

**Comment by Qballl** [comment]
Well this doesn't seem good

**Comment by Qballl** [comment]
Revert to the old version

**Comment by smuggufo** [comment]
So whats the news?

**Comment by Qballl** [comment]
Not much haven't had a lot of time to work on it

**Comment by Qballl** [comment]
Hey Im still working on this dont worry

**Comment by Qballl** [comment]
This no longer happens correct? If I remember I just removed the feature and planned on fixing it at a latter time.

**Comment by Qballl** [comment]
Im gonna close this now if it still happens you can comment on the closed issue
