### ISSUE TITLE
Doesn't work on 1.17.1

### ISSUE THREAD

**Issue by Crazy-Dog4110** [Qballl/StaffPlus#203]
My server is running 1.17.1 and staff+ doesnt work

**Comment by Qballl** [comment]
Do you have a log that could help me figure out anything?

**Comment by Crazy-Dog4110** [comment]
See I used to have it on my server but when i type /plugins Staff+ is in red

**Comment by Qballl** [comment]
That tells me nothing

**Comment by Crazy-Dog4110** [comment]
I think it means Does not work with this version

**Comment by Crazy-Dog4110** [comment]
or not compatible

**Comment by Qballl** [comment]
I NEED THE LOG TO KNOW WHY

**Comment by Crazy-Dog4110** [comment]
goodbye

**Comment by Crazy-Dog4110** [comment]
how do I get a log

**Comment by Qballl** [comment]
My best guess is you downloaded the wrong version but without the log that's all Im doing guessing as I have tested on 1.17.

**Comment by Qballl** [comment]
> how do I get a log

root/logs/latest.log

**Comment by Crazy-Dog4110** [comment]
ok let me download the latest

**Comment by Qballl** [comment]
3.3.7.0 is latest

**Comment by Crazy-Dog4110** [comment]
Yeah I am rebooting my server

**Comment by Crazy-Dog4110** [comment]
here
[latest.log](https://github.com/Qballl/StaffPlus/files/7765584/latest.log)

**Comment by Qballl** [comment]
Looks like it's loading properly now

**Comment by Crazy-Dog4110** [comment]
[22:44:23] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:44:23] [main/INFO]: Reloading ResourceManager: Default, bukkit
[22:44:24] [Worker-Main-1/INFO]: Loaded 7 recipes
[22:44:26] [Server thread/INFO]: Starting minecraft server version 1.17.1
[22:44:26] [Server thread/INFO]: Loading properties
[22:44:26] [Server thread/INFO]: This server is running Paper version git-Paper-400 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4ac995a on ver/1.17.1)
[22:44:26] [Server thread/INFO]: Server Ping Player Sample Count: 12
[22:44:26] [Server thread/INFO]: Using 4 threads for Netty based IO
[22:44:26] [Server thread/INFO]: Default game type: SURVIVAL
[22:44:26] [Server thread/INFO]: Generating keypair
[22:44:26] [Server thread/INFO]: Starting Minecraft server on *:25575
[22:44:26] [Server thread/INFO]: Using epoll channel type
[22:44:26] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[22:44:26] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[22:44:26] [Server thread/ERROR]: Could not load 'plugins/EssentialsXSpawn-2.19.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[patched_1.17.1.jar:git-Paper-400]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:158) ~[patched_1.17.1.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-400]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-400]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-400]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-400]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598) ~[?:?]
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[patched_1.17.1.jar:git-Paper-400]
	... 6 more
[22:44:27] [Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[22:44:32] [Server thread/WARN]: Legacy plugin OnePlayerSleep v1.3 does not specify an api-version.
[22:44:32] [Server thread/WARN]: Legacy plugin LuckPermsGUI v3.5 does not specify an api-version.
[22:44:33] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.0
[22:44:33] [Server thread/INFO]: [ClearLag] Loading ClearLag v3.2.2
[22:44:33] [Server thread/INFO]: [OnePlayerSleep] Loading OnePlayerSleep v1.3
[22:44:33] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v4.1.1
[22:44:33] [Server thread/INFO]: [ViaVersion] ViaVersion 4.1.1 is now loaded, injecting!
[22:44:33] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading 1.12 -> 1.13 mappings...
[22:44:33] [Via-Mappingloader-1/INFO]: [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
[22:44:33] [Via-Mappingloader-2/INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
[22:44:33] [Via-Mappingloader-3/INFO]: [ViaVersion] Loading 1.14 -> 1.15 mappings...
[22:44:33] [Via-Mappingloader-4/INFO]: [ViaVersion] Loading 1.15 -> 1.16 mappings...
[22:44:33] [Via-Mappingloader-5/INFO]: [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
[22:44:33] [Via-Mappingloader-6/INFO]: [ViaVersion] Loading 1.16.2 -> 1.17 mappings...
[22:44:33] [Via-Mappingloader-7/INFO]: [ViaVersion] Loading 1.17 -> 1.18 mappings...
[22:44:33] [Server thread/INFO]: [StaffPlus] Loading StaffPlus v3.3.7.1
[22:44:33] [Server thread/INFO]: Hooked into PlaceholderAPI 2.11.0
[22:44:33] [Server thread/INFO]: [ViaBackwards] Loading ViaBackwards v4.1.1
[22:44:33] [Server thread/INFO]: [ViaBackwards] Loading translations...
[22:44:35] [Via-Mappingloader-8/INFO]: [ViaBackwards] Loading 1.10 -> 1.9.4 mappings...
[22:44:35] [Via-Mappingloader-9/INFO]: [ViaBackwards] Loading 1.11 -> 1.10 mappings...
[22:44:35] [Via-Mappingloader-10/INFO]: [ViaBackwards] Loading 1.12 -> 1.11 mappings...
[22:44:36] [Server thread/INFO]: [ViaRewind] Loading ViaRewind v2.0.2
[22:44:36] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.3.74
[22:44:37] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[22:44:37] [Server thread/INFO]: [LuckPermsGUI] Loading LuckPermsGUI v3.5
[22:44:37] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0-SNAPSHOT-b538
[22:44:38] [Via-Mappingloader-10/INFO]: [ViaBackwards] Loading 1.13.2 -> 1.13 mappings...
[22:44:39] [Via-Mappingloader-10/INFO]: [ViaBackwards] Loading 1.14 -> 1.13.2 mappings...
[22:44:39] [Via-Mappingloader-2/INFO]: [ViaBackwards] Loading 1.15 -> 1.14 mappings...
[22:44:39] [Via-Mappingloader-3/INFO]: [ViaBackwards] Loading 1.13 -> 1.12 mappings...
[22:44:39] [Via-Mappingloader-0/INFO]: [ViaBackwards] Loading 1.17 -> 1.16.2 mappings...
[22:44:39] [Via-Mappingloader-6/INFO]: [ViaBackwards] Loading 1.16.2 -> 1.16 mappings...
[22:44:39] [Via-Mappingloader-5/INFO]: [ViaBackwards] Loading 1.16 -> 1.15 mappings...
[22:44:39] [Via-Mappingloader-4/INFO]: [ViaBackwards] Loading 1.18 -> 1.17 mappings...
[22:44:40] [Server thread/INFO]: [LibsDisguises] Loading LibsDisguises v10.0.26
[22:44:41] [Server thread/INFO]: [Vault] Loading Vault v1.7.3-b131
[22:44:41] [Server thread/INFO]: [LPC] Loading LPC v3.2.0
[22:44:41] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.2.8+6008-1246d61
[22:44:41] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@42de41b0]
[22:44:41] [Server thread/INFO]: [Essentials] Loading Essentials v2.19.0
[22:44:41] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.6-SNAPSHOT+2121-32d16a7
[22:44:41] [Server thread/INFO]: [Shopkeepers] Loading Shopkeepers v2.13.3
[22:44:41] [Server thread/INFO]: [Shopkeepers] Loaded all plugin classes (271 ms)
[22:44:41] [Server thread/INFO]: [Shopkeepers] Loading config.
[22:44:41] [Server thread/INFO]: [Shopkeepers] Loading language file: language-en-default.yml
[22:44:41] [Server thread/INFO]: [Shopkeepers] Registering WorldGuard flag 'allow-shop'.
[22:44:41] [Server thread/INFO]: [Shopkeepers] Registering defaults.
[22:44:41] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat v2.19.0
[22:44:41] [Server thread/INFO]: [Parkour] Loading Parkour v6.7.1
[22:44:41] [Server thread/INFO]: [SuperVanish] Loading SuperVanish v6.2.6
[22:44:41] [Server thread/INFO]: [MineResetLite] Loading MineResetLite v4.2.14-VK
[22:44:41] [Server thread/INFO]: [GriefPrevention] Loading GriefPrevention v16.17.1-2b69191
[22:44:41] [Server thread/INFO]: [CoreProtect] Loading CoreProtect v20.1
[22:44:41] [Server thread/INFO]: [Skript] Loading Skript v2.6
[22:44:41] [Server thread/INFO]: [EssentialsDiscord] Loading EssentialsDiscord v2.19.0
[22:44:41] [Server thread/INFO]: [SkQuery] Loading SkQuery v4.1.4
[22:44:41] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[22:44:41] [Server thread/INFO]: [ViaRewind] Enabling ViaRewind v2.0.2
[22:44:42] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.3.74
[22:44:42] [Server thread/INFO]:         __    
[22:44:42] [Server thread/INFO]:   |    |__)   LuckPerms v5.3.74
[22:44:42] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[22:44:42] [Server thread/INFO]: 
[22:44:42] [Server thread/INFO]: [LuckPerms] Loading configuration...
[22:44:43] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[22:44:43] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[22:44:44] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[22:44:44] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 2329ms)
[22:44:44] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0-SNAPSHOT-b538
[22:44:44] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[22:44:44] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[22:44:44] [Server thread/WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials v2.19.0 which is not a depend, softdepend or loadbefore of this plugin.
[22:44:44] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[22:44:44] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[22:44:44] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131
[22:44:44] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[22:44:44] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.8+6008-1246d61
[22:44:44] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[22:44:44] [Server thread/INFO]: WEPIF: Vault detected! Using Vault for permissions
[22:44:44] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_17_R1_2.PaperweightAdapter as the Bukkit adapter
[22:44:46] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[22:44:46] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[22:44:46] [Server thread/WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[22:44:46] [Server thread/WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[22:44:46] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[22:44:46] [Server thread/INFO]: Preparing level "world"
[22:44:46] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[22:44:47] [Server thread/INFO]: Preparing spawn area: 0%
[22:44:47] [Server thread/INFO]: Preparing spawn area: 0%
[22:44:47] [Server thread/INFO]: Preparing spawn area: 0%
[22:44:48] [Server thread/INFO]: Time elapsed: 1356 ms
[22:44:48] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[22:44:48] [Server thread/INFO]: Preparing spawn area: 0%
[22:44:48] [Server thread/INFO]: Preparing spawn area: 0%
[22:44:49] [Server thread/INFO]: Preparing spawn area: 0%
[22:44:49] [Server thread/INFO]: Preparing spawn area: 0%
[22:44:50] [Server thread/INFO]: Time elapsed: 1793 ms
[22:44:50] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[22:44:51] [Server thread/INFO]: Preparing spawn area: 0%
[22:44:51] [Server thread/INFO]: Preparing spawn area: 0%
[22:44:51] [Server thread/INFO]: Preparing spawn area: 0%
[22:44:51] [Server thread/INFO]: Time elapsed: 1415 ms
[22:44:51] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.0
[22:44:51] [Server thread/WARN]: [PlaceholderAPI] Loaded class com.viaversion.viaversion.api.type.Type from ViaVersion v4.1.1 which is not a depend, softdepend or loadbefore of this plugin.
[22:44:51] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[22:44:51] [Server thread/INFO]: [ClearLag] Enabling ClearLag v3.2.2
[22:44:51] [Server thread/INFO]: [ClearLag] Using version-adapter: LatestVersionAdapter
[22:44:51] [Server thread/INFO]: [ClearLag] Loading modules...
[22:44:51] [Server thread/WARN]: [ClearLag] Clearlag failed to use the internal TPS tracker during initialization. Reverted to estimation... (net.minecraft.server.v1_17_R1.MinecraftServer)
[22:44:51] [Server thread/INFO]: [ClearLag] Modules enabed, loading config values
[22:44:51] [Server thread/INFO]: [ClearLag] Modules have been loaded!
[22:44:51] [Server thread/INFO]: [ClearLag] Clearlag is now enabled!
[22:44:51] [Thread-12/INFO]: [ClearLag] Checking for updates compatible with your bukkit version [1.17]...
[22:44:51] [Server thread/INFO]: [OnePlayerSleep] Enabling OnePlayerSleep v1.3*
[22:44:51] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.1.1
[22:44:51] [Server thread/INFO]: [StaffPlus] Enabling StaffPlus v3.3.7.1
[22:44:51] [Server thread/INFO]: [Staff+] Version protocol set to 'v1_17_R1'.
[22:44:51] [Thread-12/INFO]: [ClearLag] No updates found!
[22:44:52] [Server thread/INFO]: [Staff+] Staff+ has been enabled! Initialization took 144ms.
[22:44:52] [Server thread/INFO]: [Staff+] Plugin created by Shortninja continued by Qball.
[22:44:52] [Server thread/INFO]: [ViaBackwards] Enabling ViaBackwards v4.1.1
[22:44:52] [Server thread/INFO]: [LuckPermsGUI] Enabling LuckPermsGUI v3.5*
[22:44:52] [Server thread/INFO]: *********************************************************************
[22:44:52] [Server thread/INFO]: [INFO] Initializing LuckPermsGUI Version: 3.5
[22:44:52] [Server thread/INFO]: [INFO] Created by: BGHDDevelopment
[22:44:52] [Server thread/INFO]: [INFO] Website: https://bghddevelopment.com
[22:44:52] [Server thread/INFO]: [INFO] Spigot: https://spigotmc.org/resources/53460
[22:44:52] [Server thread/INFO]: [INFO] Support: https://bghddevelopment.com/discord
[22:44:52] [Server thread/INFO]: [INFO] Suggestions/Feedback: https://feedback.bghddevelopment.com
[22:44:52] [Server thread/INFO]: [INFO] Wiki: https://wiki.bghddevelopment.com
[22:44:52] [Server thread/INFO]: *********************************************************************
[22:44:52] [Server thread/INFO]: [INFO] Plugin Loading...
[22:44:52] [Server thread/INFO]: [INFO] Registering Managers...
[22:44:52] [Server thread/INFO]: [INFO] Managers Registered!
[22:44:52] [Server thread/INFO]: [INFO] Registering Listeners...
[22:44:52] [Server thread/ERROR]: Error occurred while enabling LuckPermsGUI v3.5 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
	at me.AsVaidas.LuckPemsGUI.groups.GroupsGUI.<clinit>(GroupsGUI.java:46) ~[LuckPerms-GUI.jar:?]
	at me.AsVaidas.LuckPemsGUI.Main.registerEvents(Main.java:113) ~[LuckPerms-GUI.jar:?]
	at me.AsVaidas.LuckPemsGUI.Main.onEnable(Main.java:85) ~[LuckPerms-GUI.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-400]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-400]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-400]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-400]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-400]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-400]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-400]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-400]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-400]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
[22:44:52] [Server thread/INFO]: [LuckPermsGUI] Disabling LuckPermsGUI v3.5
[22:44:52] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.26
[22:44:52] [Server thread/INFO]: [LibsDisguises] File Name: LibsDisguises-10.0.26-Free.jar
[22:44:52] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_17_R1
[22:44:52] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #972
[22:44:52] [Server thread/INFO]: [LibsDisguises] Build Date: 16/07/2021 20:00
[22:44:52] [Server thread/WARN]: [LibsDisguises] If you own the plugin, place the premium jar downloaded from https://www.spigotmc.org/resources/libs-disguises.32453/ in plugins/LibsDisguises/
[22:44:52] [Server thread/INFO]: [LibsDisguises] You are running the free version, commands limited to non-players and operators. (Console, Command Blocks, Admins)
[22:44:54] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise libraryaddict
[22:44:54] [Server thread/INFO]: [LibsDisguises] Loaded 1 custom disguise
[22:44:54] [Server thread/INFO]: [LibsDisguises] Config is up to date!
[22:44:54] [Server thread/INFO]: [LPC] Enabling LPC v3.2.0
[22:44:54] [Server thread/INFO]: [LPC] Hooked into PlaceholderAPI.
[22:44:54] [Server thread/INFO]: [Essentials] Enabling Essentials v2.19.0
[22:44:55] [Server thread/INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[22:44:55] [Server thread/INFO]: [Essentials] No kits found to migrate.
[22:44:55] [Server thread/INFO]: [Essentials] Loaded 36837 items from items.json.
[22:44:55] [Server thread/INFO]: [Essentials] Using locale en_US
[22:44:55] [Server thread/INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[22:44:55] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[22:44:55] [Server thread/INFO]: [Vault] [Economy] Essentials Economy hooked.
[22:44:55] [Server thread/INFO]: [Essentials] Using Vault based permissions (LuckPerms)
[22:44:55] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v7.0.6-SNAPSHOT+2121-32d16a7
[22:44:55] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[22:44:55] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[22:44:55] [Server thread/INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[22:44:55] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[22:44:55] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[22:44:55] [Server thread/INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[22:44:55] [Server thread/INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[22:44:55] [Server thread/INFO]: [WorldGuard] (world_nether) Lava fire is PERMITTED.
[22:44:55] [Server thread/INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[22:44:55] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[22:44:55] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[22:44:55] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[22:44:55] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is PERMITTED.
[22:44:55] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[22:44:55] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[22:44:55] [Server thread/INFO]: [WorldGuard] Loading region data...
[22:44:55] [Server thread/INFO]: [Shopkeepers] Enabling Shopkeepers v2.13.3
[22:44:55] [Server thread/INFO]: [Shopkeepers] Loading data of 5 shopkeepers..
[22:44:56] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat v2.19.0
[22:44:56] [Server thread/INFO]: [EssentialsChat] Starting Metrics. Opt-out using the global bStats config.
[22:44:56] [Server thread/INFO]: [Parkour] Enabling Parkour v6.7.1
[22:44:56] [Server thread/INFO]: [Parkour] [Vault] Successfully linked. Version: 1.7.3-b131
[22:44:56] [Server thread/INFO]: [Parkour] Enabled Parkour v6.7.1
[22:44:56] [Thread-14/INFO]: [Parkour] Checking for update...
[22:44:56] [Thread-14/INFO]: [Parkour] No update available.
[22:44:56] [Server thread/INFO]: [SuperVanish] Enabling SuperVanish v6.2.6
[22:44:56] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: supervanish [6.2.6]
[22:44:56] [Server thread/INFO]: [SuperVanish] Hooked into PlaceholderAPI
[22:44:56] [Server thread/INFO]: [SuperVanish] Hooked into Essentials
[22:44:56] [Server thread/INFO]: [MineResetLite] Enabling MineResetLite v4.2.14-VK
[22:44:56] [Server thread/INFO]: [MineResetLite] Loading mine from file 'iron.mine.yml'...
[22:44:56] [Server thread/INFO]: [MineResetLite] Loading mine from file 'Netherite.mine.yml'...
[22:44:56] [Server thread/INFO]: [MineResetLite] Loading mine from file 'stone.mine.yml'...
[22:44:56] [Server thread/INFO]: [MineResetLite] Loading mine from file 'diamonds.mine.yml'...
[22:44:56] [Server thread/INFO]: [MineResetLite] Loading mine from file 'wood.mine.yml'...
[22:44:56] [Server thread/INFO]: [MineResetLite] MineResetLite version 4.2.14-VK enabled!
[22:44:56] [Server thread/INFO]: [GriefPrevention] Enabling GriefPrevention v16.17.1-2b69191
[22:44:56] [Server thread/INFO]: [GriefPrevention] Finished loading configuration.
[22:44:56] [Server thread/INFO]: [GriefPrevention] 7 total claims loaded.
[22:44:56] [Server thread/INFO]: [GriefPrevention] Customizable messages loaded.
[22:44:56] [Server thread/INFO]: [GriefPrevention] Successfully hooked into WorldGuard.
[22:44:56] [Server thread/INFO]: [GriefPrevention] Finished loading data (File Mode).
[22:44:56] [Server thread/INFO]: [GriefPrevention] Boot finished.
[22:44:56] [Server thread/INFO]: [CoreProtect] Enabling CoreProtect v20.1
[22:44:56] [Server thread/INFO]: [CoreProtect] CoreProtect has been successfully enabled! 
[22:44:56] [Server thread/INFO]: [CoreProtect] Using SQLite for data storage.
[22:44:56] [Server thread/INFO]: --------------------
[22:44:56] [Server thread/INFO]: [CoreProtect] Enjoy CoreProtect? Join our Discord!
[22:44:56] [Server thread/INFO]: [CoreProtect] Discord: www.coreprotect.net/discord/
[22:44:56] [Server thread/INFO]: --------------------
[22:44:56] [Server thread/INFO]: [Skript] Enabling Skript v2.6
[22:44:57] [Thread-18/INFO]: [Skript] You're currently running the latest stable version of Skript.
[22:45:02] [Server thread/INFO]: [Skript] Loaded 143125 aliases in 6036ms
[22:45:03] [Server thread/INFO]: [Skript]  ~ created by & ? Peter G?ttinger aka Njol ~
[22:45:03] [Server thread/INFO]: [EssentialsDiscord] Enabling EssentialsDiscord v2.19.0
[22:45:03] [Server thread/INFO]: [EssentialsDiscord] Starting Metrics. Opt-out using the global bStats config.
[22:45:03] [Server thread/INFO]: [EssentialsDiscord] Attempting to login to Discord...
[22:45:03] [Server thread/ERROR]: [EssentialsDiscord] An error occurred while logging into Discord, which has caused the plugin to disable itself: 
No token provided! Please follow the tutorial in the config in order to setup the plugin.
[22:45:03] [Server thread/INFO]: [SkQuery] Enabling SkQuery v4.1.4
[22:45:03] [Server thread/INFO]: [skQuery] Locating classes from SkQuery...
[22:45:03] [Server thread/INFO]: [skQuery] Beginning to process a total of 138 from SkQuery
[22:45:03] [Server thread/INFO]: [skQuery] Out of 138 classes, 136 classes were loaded from SkQuery
[22:45:03] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[22:45:03] [Server thread/INFO]: Running delayed init tasks
[22:45:03] [Craft Scheduler Thread - 8 - Essentials/INFO]: [Essentials] Fetching version information...
[22:45:03] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.17.1 (756)
[22:45:03] [Craft Scheduler Thread - 13 - Vault/INFO]: [Vault] Checking for Updates ... 
[22:45:03] [Craft Scheduler Thread - 13 - Vault/INFO]: [Vault] No new version available
[22:45:03] [Server thread/INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[22:45:03] [Server thread/INFO]: [CoreProtect] WorldEdit logging successfully initialized.
[22:45:03] [Server thread/INFO]: [Skript] Loading variables...
[22:45:03] [Server thread/INFO]: [Skript] Loaded 0 variables in 0.0 seconds
[22:45:03] [Server thread/INFO]: [Skript] All scripts loaded without errors.
[22:45:03] [Server thread/WARN]: [Skript] No scripts were found, maybe you should write some ;) (config.sk, line 210: databases:')
[22:45:03] [Server thread/INFO]: [Skript] Finished loading.
[22:45:03] [Server thread/INFO]: 0 placeholder hook(s) registered!
[22:45:03] [Server thread/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[22:45:03] [Server thread/INFO]: Done (37.793s)! For help, type "help"
[22:45:03] [Server thread/INFO]: Timings Reset
[22:45:03] [Craft Scheduler Thread - 8 - Essentials/WARN]: [Essentials] There is a new EssentialsX version available for download: 2.19.2.
[22:45:03] [Craft Scheduler Thread - 8 - Essentials/WARN]: [Essentials] Download it here: https://essentialsx.net/downloads.html?branch=stable
[22:45:04] [Craft Scheduler Thread - 6 - StaffPlus/INFO]: [StaffPlus] You are using the latest version thanks
[22:45:04] [Thread-21/INFO]: --------------------
[22:45:04] [Thread-21/INFO]: [CoreProtect] Version 20.3 is now available.
[22:45:04] [Thread-21/INFO]: [CoreProtect] Download: www.coreprotect.net/download/
[22:45:04] [Thread-21/INFO]: --------------------

**Comment by Crazy-Dog4110** [comment]
ok let me have a look on the client end

**Comment by Crazy-Dog4110** [comment]
of minecraft

**Comment by Crazy-Dog4110** [comment]
Yeah all good thx
