### ISSUE TITLE
Failed to find version enum for 'org.bukkit.craftbukkit.v1_20_R3'/'v1_20_R3.'

### ISSUE THREAD

**Issue by Jernee** [Qballl/StaffPlus#221]
[07:22:46] [Server thread/ERROR]: [StaffPlus] [ReflectionHelper] Failed to find version enum for 'org.bukkit.craftbukkit.v1_20_R3'/'v1_20_R3.'
[07:22:46] [Server thread/INFO]: [StaffPlus] [ReflectionHelper] Generating dynamic constant...
[07:22:46] [Server thread/WARN]: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='$VALUES', types=[]}] in class class org.inventivetalent.packetlistener.reflection.minecraft.Minecraft$Version
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:186)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:39)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:88)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.resolve(FieldResolver.java:85)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.reflection.minecraft.Minecraft$Version.getVersion(Minecraft.java:198)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:61)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:43)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveSilent(ClassResolver.java:44)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.channel.ChannelAbstract.<clinit>(ChannelAbstract.java:51)
[07:22:46] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[07:22:46] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(ClassResolver.java:63)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(ClassResolver.java:36)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:78)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(ClassResolver.java:55)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.ChannelInjector.newChannelInstance(ChannelInjector.java:71)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.ChannelInjector.inject(ChannelInjector.java:58)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:59)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:102)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:178)
[07:22:46] [Server thread/WARN]: 	at Staff+.jar//net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:103)
[07:22:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[07:22:46] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[07:22:46] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[07:22:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[07:22:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653)
[07:22:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564)
[07:22:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[07:22:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[07:22:46] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:346)
[07:22:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
[07:22:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[07:22:46] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[07:22:46] [Server thread/INFO]: [StaffPlus] [ReflectionHelper] Version is UNKNOWN (-1)
[07:22:46] [Server thread/ERROR]: Error occurred while enabling StaffPlus v3.2.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.inventivetalent.packetlistener.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:43) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveSilent(ClassResolver.java:44) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.channel.ChannelAbstract.<clinit>(ChannelAbstract.java:51) ~[Staff+.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(ClassResolver.java:63) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(ClassResolver.java:36) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:78) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(ClassResolver.java:55) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.ChannelInjector.newChannelInstance(ChannelInjector.java:71) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.ChannelInjector.inject(ChannelInjector.java:58) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:59) ~[Staff+.jar:?]
	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:102) ~[Staff+.jar:?]
	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:178) ~[Staff+.jar:?]
	at net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:103) ~[Staff+.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.UNKNOWN.Entity', types=[]}]
	at org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:68) ~[Staff+.jar:?]
	... 27 more
Caused by: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.UNKNOWN.Entity', types=[]}]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:68) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:36) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:88) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(ClassResolver.java:55) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:46) ~[Staff+.jar:?]
	at org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:65) ~[Staff+.jar:?]
	... 27 more
[07:22:46] [Server thread/INFO]: [StaffPlus] Disabling StaffPlus v3.2.2
[07:22:46] [Server thread/INFO]: [Staff+] Staff+ is now disabling!

**Comment by Jernee** [comment]
Had an older version from the old dev.
