### ISSUE TITLE
Server crash when I run command /staff

### ISSUE THREAD

**Issue by Samir-driod** [Qballl/StaffPlus#224]
I have updated my server to version 1.20.6 paper (and downloaded the newest version of plugin). When I join the server and type "/staff" the server crashes. Any idea what could be a problem. 

Crash report:

---- Minecraft Crash Report ----

Time: 2024-07-12 16:30:00
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: Could not initialize class net.shortninja.staffplus.player.User
	at Staff+ (1).jar//net.shortninja.staffplus.server.data.Load.loadUser(Load.java:84)
	at Staff+ (1).jar//net.shortninja.staffplus.server.data.Load.<init>(Load.java:39)
	at Staff+ (1).jar//net.shortninja.staffplus.player.attribute.mode.ModeCoordinator.addMode(ModeCoordinator.java:63)
	at Staff+ (1).jar//net.shortninja.staffplus.server.command.cmd.mode.ModeCmd.toggleMode(ModeCmd.java:60)
	at Staff+ (1).jar//net.shortninja.staffplus.server.command.cmd.mode.ModeCmd.execute(ModeCmd.java:51)
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448)
	at net.minecraft.commands.Commands.performCommand(Commands.java:355)
	at net.minecraft.commands.Commands.performCommand(Commands.java:342)
	at net.minecraft.commands.Commands.performCommand(Commands.java:337)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3 [in thread "Server thread"]
	at Staff+ (1).jar//net.shortninja.staffplus.player.User.<clinit>(User.java:45)
	at Staff+ (1).jar//net.shortninja.staffplus.server.data.Load.loadUser(Load.java:84)
	at Staff+ (1).jar//net.shortninja.staffplus.server.data.Load.<init>(Load.java:39)
	at Staff+ (1).jar//net.shortninja.staffplus.server.listener.player.PlayerJoin.manageUser(PlayerJoin.java:76)
	at Staff+ (1).jar//net.shortninja.staffplus.server.listener.player.PlayerJoin.onJoin(PlayerJoin.java:52)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor913.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347)
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153)
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22)
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13)
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 22, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 325625344 bytes (310 MiB) / 1073741824 bytes (1024 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Virtual memory max (MB): 33742.99
	Virtual memory used (MB): 23950.59
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 974.13
	JVM Flags: 2 total; -Xmx1024M -Xms1024M
	CraftBukkit Information: 
   BrandInfo: Paper (papermc:paper) version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z)
   Running: Paper version 1.20.6-148-20f5165 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) true

**Comment by erneto13** [comment]
hi @Samir-driod, I recommend you [read this](https://www.spigotmc.org/threads/a-reflection.219197/) and look for the fork of the plugin found on the web. peace! 👍

**Comment by BalinGrant** [comment]
> hi @Samir-driod, I recommend you [read this](https://www.spigotmc.org/threads/a-reflection.219197/) and look for the fork of the plugin found on the web. peace! 👍 

This repository is the continuation of ShortNinja's plugin, by Qball. 
This version is still maintained for the most part, and includes updates well past what ShortNinja was able to.

**Comment by Qballl** [comment]
Can you provide the startup log?

**Comment by Samir-driod** [comment]
I am using Paper version 1.21-124-master@df3b654 (2024-08-02T00:02:38Z) (Implementing API version 1.21-R0.1-SNAPSHOT).

This is startup log for this plugin:

[21:18:56 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins\.paper-remapped\Staff+ (2).jar' in 'plugins\.paper-remapped'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'StaffPlus'.
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.21.jar:1.21-124-df3b654]   
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.jar:1.21-124-df3b654]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by Samir-driod** [comment]
After update to Paper version 1.21-124-master@df3b654 (2024-08-02T00:02:38Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
the error has changed: 

[21:37:22 INFO]: [StaffPlus] Enabling StaffPlus v3.3.14.1
[21:37:22 INFO]: [Staff+] This version of Minecraft is not supported! If you have just updated to a brand new server version, check the Spigot plugin page.
[21:37:22 INFO]: [StaffPlus] Disabling StaffPlus v3.3.14.1
[21:37:22 INFO]: [Staff+] Staff+ is now disabling!
[21:37:22 ERROR]: Error occurred while disabling StaffPlus v3.3.14.1
java.lang.NullPointerException: Cannot invoke "net.shortninja.staffplus.server.hook.HookHandler.disableAll()" because "this.hookHandler" is null
        at Staff+ (2).jar/net.shortninja.staffplus.StaffPlus.stop(StaffPlus.java:397) ~[Staff+ (2).jar:?]
        at Staff+ (2).jar/net.shortninja.staffplus.StaffPlus.onDisable(StaffPlus.java:170) ~[Staff+ (2).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.jar:1.21-124-df3b654]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at Staff+ (2).jar/net.shortninja.staffplus.StaffPlus.start(StaffPlus.java:189) ~[Staff+ (2).jar:?]
        at Staff+ (2).jar/net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:140) ~[Staff+ (2).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-124-df3b654]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[21:37:22 ERROR]: Error occurred while enabling StaffPlus v3.3.14.1 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at Staff+ (2).jar/net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:144) ~[Staff+ (2).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-124-df3b654]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
