### ISSUE TITLE
Error message when using compass

### ISSUE THREAD

**Issue by EvilSlime** [Qballl/StaffPlus#27]
<details>
  <summary>Error</summary>
  `[07:05:31] [Server thread/WARN]: Excessive velocity set detected: tried to set velocity of entity #137 to (4.715779119522306,0.669422582444794,-1.5209538789819925).[07:05:31] [Server thread/WARN]: java.lang.Exception: Stack trace[07:05:31] [Server thread/WARN]: at java.lang.Thread.dumpStack(Thread.java:1336)[07:05:31] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.setVelocity(CraftEntity.java:213)[07:05:31] [Server thread/WARN]: at net.shortninja.staffplus.player.attribute.mode.handler.GadgetHandler.onCompass(GadgetHandler.java:94)[07:05:31] [Server thread/WARN]: at net.shortninja.staffplus.server.listener.player.PlayerInteract.handleInteraction(PlayerInteract.java:71)[07:05:31] [Server thread/WARN]: at net.shortninja.staffplus.server.listener.player.PlayerInteract.onInteract(PlayerInteract.java:53)[07:05:31] [Server thread/WARN]: at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)[07:05:31] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[07:05:31] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)[07:05:31] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)[07:05:31] [Server thread/WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)[07:05:31] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)[07:05:31] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)[07:05:31] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)[07:05:31] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)[07:05:31] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195)[07:05:31] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191)[07:05:31] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:721)[07:05:31] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)[07:05:31] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)[07:05:31] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)[07:05:31] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[07:05:31] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)[07:05:31] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)[07:05:31] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)[07:05:31] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)[07:05:31] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)[07:05:31] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)[07:05:31] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)`
</details>

**Comment by Qballl** [comment]
I will look into this but in the future use a pasting service such as pastebin.

**Comment by Qballl** [comment]
Is this still happening?

**Comment by BalinGrant** [comment]
Closing due to inactivity.
