### ISSUE TITLE
Error when using blocked command.

### ISSUE THREAD

**Issue by EvilSlime** [Qballl/StaffPlus#31]
[10:14:36] [Server thread/WARN]: Excessive velocity set detected: tried to set velocity of entity #26 to (0.63063370309005,2.260443604160592,4.415053323000347).[10:14:36] [Server thread/WARN]: java.lang.Exception: Stack trace[10:14:36] [Server thread/WARN]: at java.lang.Thread.dumpStack(Thread.java:1336)[10:14:36] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.setVelocity(CraftEntity.java:213)[10:14:36] [Server thread/WARN]: at net.shortninja.staffplus.player.attribute.mode.handler.GadgetHandler.onCompass(GadgetHandler.java:94)[10:14:36] [Server thread/WARN]: at net.shortninja.staffplus.server.listener.player.PlayerInteract.handleInteraction(PlayerInteract.java:71)[10:14:36] [Server thread/WARN]: at net.shortninja.staffplus.server.listener.player.PlayerInteract.onInteract(PlayerInteract.java:53)[10:14:36] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[10:14:36] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[10:14:36] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[10:14:36] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)[10:14:36] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)[10:14:36] [Server thread/WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)[10:14:36] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)[10:14:36] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)[10:14:36] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)[10:14:36] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)[10:14:36] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195)[10:14:36] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191)[10:14:36] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:721)[10:14:36] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)[10:14:36] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)[10:14:36] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)[10:14:36] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[10:14:36] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)[10:14:36] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)[10:14:36] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)[10:14:36] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)[10:14:36] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)[10:14:36] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)[10:14:36] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)****

**Comment by Qballl** [comment]
In the future use a pasting service for errors

**Comment by EvilSlime** [comment]
That is why it is closed.

**Comment by Qballl** [comment]
Also in this, I see no relation to StaffPlus
