### ISSUE TITLE
1.12.2 StaffPlus Error

### ISSUE THREAD

**Issue by Niko302** [Qballl/StaffPlus#43]
>
[11:58:12 WARN]: [PacketListenerAPI] An exception occured while trying to execute 'onSend' in plugin StaffPlus: null
>
[11:58:12 WARN]: java.lang.NullPointerException
>
[11:58:12 ERROR]: Could not pass event InventoryClickEvent to StaffPlus v3.2.7.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
>
[11:58:12 WARN]: [PacketListenerAPI] An exception occured while trying to execute 'onSend' in plugin StaffPlus: null

**Comment by Qballl** [comment]
Can you use pastebin to make this easier to read and tell me when this happens

**Comment by Niko302** [comment]
> 
> 
> Can you use pastebin to make this easier to read and tell me when this happens

https://pastebin.com/aYvPVRtQ
happens whenever the plugin is active can not really get any iformation at what exact action.
Also installed the PacketListenerAPI as suggested but with no luck.

**Comment by Qballl** [comment]
It looks like this is more on PackerListenerAPI side of things so gonna close it
