### ISSUE TITLE
Error 1.7.10

### ISSUE THREAD

**Issue by SkyBOx12** [Qballl/StaffPlus#45]
[10:30:33] [Server thread/ERROR]: Error occurred while enabling StaffPlus v3.2.7.1 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at org.inventivetalent.packetlistener.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:15) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveSilent(ClassResolver.java:16) ~[?:?]
	at org.inventivetalent.packetlistener.channel.ChannelAbstract.<clinit>(ChannelAbstract.java:23) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_161]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_161]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(ClassResolver.java:35) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(ClassResolver.java:8) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:50) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(ClassResolver.java:27) ~[?:?]
	at org.inventivetalent.packetlistener.ChannelInjector.newChannelInstance(ChannelInjector.java:43) ~[?:?]
	at org.inventivetalent.packetlistener.ChannelInjector.inject(ChannelInjector.java:30) ~[?:?]
	at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:31) ~[?:?]
	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:46) ~[?:?]
	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:117) ~[?:?]
	at net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:109) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.v1_7_R4.Entity', types=[]}]
	at org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:40) ~[?:?]
	... 26 more
Caused by: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.v1_7_R4.Entity', types=[]}]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:40) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:8) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:60) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(ClassResolver.java:27) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:18) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:37) ~[?:?]
	... 26 more

**Comment by Qballl** [comment]
This is actually a packetlistener issue

**Comment by SkyBOx12** [comment]
How can I fix it?

**Comment by SkyBOx12** [comment]
ok

**Comment by InventivetalentDev** [comment]
1.7 is very much outdated and not officially supported by PacketListenerAPI anymore, sorry.  
Although it *should* work judging by the errors. Would you mind providing some more specific information on your server version (/version)?

**Comment by Qballl** [comment]
> 1.7 is very much outdated and not officially supported by PacketListenerAPI anymore, sorry.
> Although it _should_ work judging by the errors. Would you mind providing some more specific information on your server version (/version)?

Thanks for helping knowing that packetlistner doesn't support 1.7 gives me yet another reason to drop 1.7 support

**Comment by Qballl** [comment]
Closing this due to lack of reply from @SkyBOx12 this does seems to be on packetlistenerapi's end so if issue persists contact InventivetalentDev
