### ISSUE TITLE
Console Warnings (staffplus) (list?)

### ISSUE THREAD

**Issue by ghost** [Qballl/StaffPlus#69]
Dear Qballl, I have a warning in my console. And I was wondering if you may have the awnser, problem, sollution for it. 

Thank you in advance! 

Warning: https://gyazo.com/2e178b32321a0856acf5352c1e200f87

- Nick

**Comment by Qballl** [comment]
Can you get me more from that error if there is more

**Comment by Valtorian** [comment]
There is no more info, thats all. Are you missing stuff?

**Comment by Qballl** [comment]
No just looks like there would be more before ot

**Comment by Valtorian** [comment]
**The full server restart:** 

[Pterodactyl Daemon] Server marked as STOPPING
stop=> [13:02:15 INFO]: Stopping the server
[13:02:15 INFO]: Stopping server
[13:02:15 INFO]: [Dynmap-WorldGuard] Disabling Dynmap-WorldGuard v0.90
[13:02:15 INFO]: [OpenAudioMc] Disabling OpenAudioMc v5.2
[13:02:15 INFO]: [CombatLogX] Disabling CombatLogX v9.6.0.2
[13:02:15 INFO]: [WorldGuard] Disabling WorldGuard v6.2.2-SNAPSHOT;8eeab68
[13:02:15 INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
[13:02:15 INFO]: [WorldEdit] Disabling WorldEdit v6.1.7;dd00bb1
[13:02:15 INFO]: [MineSync] Disabling MineSync vS_2.1.0
[13:02:15 INFO]: [VoxelSniper] Disabling VoxelSniper v5.172.0-SNAPSHOT
[13:02:15 INFO]: [LiteBans] Disabling LiteBans v2.3.15
[13:02:15 INFO]: [LiteBans] v2.3.15 disabled.
[13:02:15 INFO]: [FastAsyncVoxelSniper] Disabling FastAsyncVoxelSniper v19.04.22-57c85d0-1271-22.0.6
[13:02:15 INFO]: [ItemRestrict] Disabling ItemRestrict v2.4.1
[13:02:15 INFO]: [ItemRestrict] ItemRestrict is disabled!
[13:02:15 INFO]: [PlayerParticles] Disabling PlayerParticles v6.4
[13:02:15 INFO]: [EssentialsSpawn] Disabling EssentialsSpawn vTeamCity
[13:02:15 INFO]: [StaffPlus] Disabling StaffPlus v3.2.8.2
[13:02:15 INFO]: [Staff+] Staff+ is now disabling!
[13:02:15 INFO]: [PacketListenerAPI] Removing channels for online players...
[13:02:15 INFO]: [PacketListenerAPI] Removing packet handlers (1)...
[13:02:15 INFO]: [Vault] Disabling Vault v1.7.1-b91
[13:02:15 INFO]: [WooMinecraft] Disabling WooMinecraft v1.1.2-S1.12.1-R0.1
[13:02:15 INFO]: [WooMinecraft] Commando's Geïnitialiseerd
[13:02:15 INFO]: [MaintenanceSpigot] Disabling MaintenanceSpigot v3.0.1
[13:02:15 INFO]: [EssentialsAntiBuild] Disabling EssentialsAntiBuild vTeamCity
[13:02:15 INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4
[13:02:15 INFO]: [React] Disabling React v6.609
[13:02:15 INFO]: [PlaceholderAPI] Unregistered placeholder hook for placeholder: react
[13:02:15 INFO]: [FastAsyncWorldEdit] Disabling FastAsyncWorldEdit v19.05.02-d89cb44-1274-22.2.0
[13:02:15 INFO]: [OldCombatMechanics] Disabling OldCombatMechanics v1.6.6
[13:02:15 INFO]: [OldCombatMechanics] OldCombatMechanics v1.6.6 has been disabled
[13:02:15 INFO]: [VotingPlugin] Disabling VotingPlugin v5.13.6
[13:02:15 INFO]: [KitAdder] Disabling KitAdder v3
[13:02:15 INFO]: [KitAdder] KitAdder plugin has been disabled!
[13:02:15 INFO]: [AntiWDL] Disabling AntiWDL v0.1
[13:02:15 INFO]: [ProtocolLib] Disabling ProtocolLib v4.4.0
[13:02:15 INFO]: [Votifier] Disabling Votifier v2.5.0
[13:02:15 INFO]: [Votifier] Votifier disabled.
[13:02:15 INFO]: [EasyBackup] Disabling EasyBackup v2.8.5
[13:02:15 INFO]: [BetterChairs] Disabling BetterChairs v0.9.5
[13:02:15 INFO]: [WorldBorder] Disabling WorldBorder v1.8.7
[13:02:15 INFO]: [WorldBorder] [CONFIG] Border-checking timed task stopped.
[13:02:15 INFO]: [ConsoleScheduler] Disabling ConsoleScheduler v1.4.8
[13:02:15 INFO]: [ConsoleScheduler] By BoomerBR & Boomclaw - v1.4.8 disabled.
[13:02:15 INFO]: [PlugMan] Disabling PlugMan v2.1.6
[13:02:15 INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.9.2
[13:02:15 INFO]: [Essentials] Disabling Essentials vTeamCity
[13:02:15 INFO]: [OpenInv] Disabling OpenInv v3.3.5
[13:02:15 INFO]: [PluginConstructorAPI] Disabling PluginConstructorAPI v1.0.51
[13:02:15 INFO]: [BlockParticles] Disabling BlockParticles v1.9.7.2
[13:02:15 INFO]: [dynmap] Disabling dynmap v3.0-beta-3-160
[13:02:15 INFO]: [dynmap] Unloaded 11 components.
[13:02:15 INFO]: [dynmap] Stopping map renderer...
[13:02:16 INFO]: [dynmap] Disabled
[13:02:16 INFO]: [CoreProtect] Disabling CoreProtect v2.14.4
[13:02:16 INFO]: Saving players
[13:02:16 INFO]: Saving worlds
[13:02:16 INFO]: Saving chunks for level 'GKD'/overworld
[13:02:16 INFO]: Saving chunks for level 'GKD_nether'/the_nether
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 19400M / 108720M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
:/home/container$ java -Xms128M -Xmx38840M -jar paperclip-1613.jar
Loading libraries, please wait...
[13:02:21 INFO]: Starting minecraft server version 1.12.2
[13:02:21 INFO]: Loading properties
[13:02:21 INFO]: Default game type: SURVIVAL
=> [13:02:21 INFO]: This server is running Paper version git-Paper-1613 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[13:02:21 INFO]: Server Ping Player Sample Count: 12
[13:02:21 INFO]: Using 3 threads for Netty based IO
[13:02:21 INFO]: Debug logging is disabled
[13:02:21 INFO]: Generating keypair
[13:02:21 INFO]: Starting Minecraft server on 0.0.0.0:25565
[13:02:21 INFO]: Using epoll channel type
[13:02:21 INFO]: Set PluginClassLoader as parallel capable
[13:02:22 INFO]: [CoreProtect] Loading CoreProtect v2.14.4
[13:02:22 INFO]: [dynmap] Loading dynmap v3.0-beta-3-160
[13:02:22 INFO]: [dynmap] version=git-Paper-1613 (MC: 1.12.2)
[13:02:22 INFO]: [dynmap] Mod Support API available
[13:02:22 INFO]: [BlockParticles] Loading BlockParticles v1.9.7.2
[13:02:22 INFO]: [PluginConstructorAPI] Loading PluginConstructorAPI v1.0.51
[13:02:22 INFO]: [OpenInv] Loading OpenInv v3.3.5
[13:02:22 INFO]: [Essentials] Loading Essentials vTeamCity
[13:02:22 INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.9.2
[13:02:22 INFO]: [PlugMan] Loading PlugMan v2.1.6
[13:02:22 INFO]: [ConsoleScheduler] Loading ConsoleScheduler v1.4.8
[13:02:22 INFO]: [WorldBorder] Loading WorldBorder v1.8.7
[13:02:22 INFO]: [BetterChairs] Loading BetterChairs v0.9.5
[13:02:22 INFO]: [EasyBackup] Loading EasyBackup v2.8.5
[13:02:22 INFO]: [Votifier] Loading Votifier v2.5.0
[13:02:22 INFO]: [ProtocolLib] Loading ProtocolLib v4.4.0
[13:02:22 INFO]: [AntiWDL] Loading AntiWDL v0.1
[13:02:22 INFO]: [KitAdder] Loading KitAdder v3
[13:02:22 INFO]: [VotingPlugin] Loading VotingPlugin v5.13.6
[13:02:22 INFO]: [OldCombatMechanics] Loading OldCombatMechanics v1.6.6
[13:02:22 INFO]: [FastAsyncWorldEdit] Loading FastAsyncWorldEdit v19.05.02-d89cb44-1274-22.2.0
[13:02:22 INFO]: [React] Loading React v6.609
[13:02:22 INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
[13:02:22 INFO]: [EssentialsAntiBuild] Loading EssentialsAntiBuild vTeamCity
[13:02:22 INFO]: [MaintenanceSpigot] Loading MaintenanceSpigot v3.0.1
[13:02:22 INFO]: [WooMinecraft] Loading WooMinecraft v1.1.2-S1.12.1-R0.1
[13:02:22 INFO]: [Vault] Loading Vault v1.7.1-b91
[13:02:22 INFO]: [StaffPlus] Loading StaffPlus v3.2.8.2
[13:02:22 INFO]: [EssentialsSpawn] Loading EssentialsSpawn vTeamCity
[13:02:22 INFO]: [PlayerParticles] Loading PlayerParticles v6.4
[13:02:22 INFO]: [ItemRestrict] Loading ItemRestrict v2.4.1
[13:02:22 INFO]: [FastAsyncVoxelSniper] Loading FastAsyncVoxelSniper v19.04.22-57c85d0-1271-22.0.6
[13:02:22 INFO]: [LiteBans] Loading LiteBans v2.3.15
[13:02:22 INFO]: [VoxelSniper] Loading VoxelSniper v5.172.0-SNAPSHOT
[13:02:22 INFO]: [MineSync] Loading MineSync vS_2.1.0
[13:02:22 INFO]: [WorldEdit] Loading WorldEdit v6.1.7;dd00bb1
[13:02:22 INFO]: [WorldGuard] Loading WorldGuard v6.2.2-SNAPSHOT;8eeab68
[13:02:22 INFO]: [CombatLogX] Loading CombatLogX v9.6.0.2
[13:02:22 INFO]: [GKD] Loading expansion 'Notifier v13.9'
[13:02:22 INFO]: [GKD] Loaded 1 expansion
[13:02:22 INFO]: [OpenAudioMc] Loading OpenAudioMc v5.2
[13:02:22 INFO]: [Dynmap-WorldGuard] Loading Dynmap-WorldGuard v0.90
[13:02:22 INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:02:22 INFO]: [ProtocolLib] Enabling ProtocolLib v4.4.0
[13:02:22 INFO]: [ProtocolLib] Started structure compiler thread.
[13:02:22 INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v19.05.02-d89cb44-1274-22.2.0
[13:02:22 INFO]: [React] Enabling React v6.609
[13:02:22 INFO]: [React] Selected R1_12
[13:02:22 INFO]: React: Language: enUS
[13:02:22 INFO]: 1.12.2
[13:02:22 INFO]: [Vault] Enabling Vault v1.7.1-b91
[13:02:22 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[13:02:22 INFO]: [Vault] [Permission] PermissionsEx found: Waiting
[13:02:22 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[13:02:22 INFO]: [Vault] [Chat] PermissionsEx found: Waiting
[13:02:22 INFO]: [Vault] Enabled Version 1.7.1-b91
[13:02:22 INFO]: [FastAsyncVoxelSniper] Enabling FastAsyncVoxelSniper v19.04.22-57c85d0-1271-22.0.6
[13:02:22 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[13:02:22 INFO]: Preparing level "GKD"
[13:02:22 INFO]: -------- World Settings For [GKD] --------
[13:02:22 INFO]: Mob Spawn Range: 4
[13:02:22 INFO]: Cactus Growth Modifier: 100%
[13:02:22 INFO]: Cane Growth Modifier: 100%
[13:02:22 INFO]: Melon Growth Modifier: 100%
[13:02:22 INFO]: Mushroom Growth Modifier: 100%
[13:02:22 INFO]: Pumpkin Growth Modifier: 100%
[13:02:22 INFO]: Sapling Growth Modifier: 100%
[13:02:22 INFO]: Wheat Growth Modifier: 100%
[13:02:22 INFO]: NetherWart Growth Modifier: 100%
[13:02:22 INFO]: Vine Growth Modifier: 100%
[13:02:22 INFO]: Cocoa Growth Modifier: 100%
[13:02:22 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[13:02:22 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:02:22 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:02:22 INFO]: Random Lighting Updates: false
[13:02:22 INFO]: Structure Info Saving: true
[13:02:22 INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[13:02:22 INFO]: Max TNT Explosions: 100
[13:02:22 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:02:22 INFO]: Item Despawn Rate: 7200
[13:02:22 INFO]: Item Merge Radius: 5.0
[13:02:22 INFO]: View Distance: 10
[13:02:22 INFO]: Arrow Despawn Rate: 600
[13:02:22 INFO]: Allow Zombie Pigmen to spawn from portal blocks: false
[13:02:22 INFO]: Experience Merge Radius: 10.0
[13:02:22 INFO]: Zombie Aggressive Towards Villager: true
[13:02:22 INFO]: Nerfing mobs spawned from spawners: false
[13:02:22 INFO]: -------- World Settings For [GKD_nether] --------
[13:02:22 INFO]: Mob Spawn Range: 4
[13:02:22 INFO]: Cactus Growth Modifier: 100%
[13:02:22 INFO]: Cane Growth Modifier: 100%
[13:02:22 INFO]: Melon Growth Modifier: 100%
[13:02:22 INFO]: Mushroom Growth Modifier: 100%
[13:02:22 INFO]: Pumpkin Growth Modifier: 100%
[13:02:22 INFO]: Sapling Growth Modifier: 100%
[13:02:22 INFO]: Wheat Growth Modifier: 100%
[13:02:22 INFO]: NetherWart Growth Modifier: 100%
[13:02:22 INFO]: Vine Growth Modifier: 100%
[13:02:22 INFO]: Cocoa Growth Modifier: 100%
[13:02:22 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[13:02:22 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:02:22 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:02:22 INFO]: Random Lighting Updates: false
[13:02:22 INFO]: Structure Info Saving: true
[13:02:22 INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[13:02:22 INFO]: Max TNT Explosions: 100
[13:02:22 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:02:22 INFO]: Item Despawn Rate: 7200
[13:02:22 INFO]: Item Merge Radius: 5.0
[13:02:22 INFO]: View Distance: 10
[13:02:22 INFO]: Arrow Despawn Rate: 600
[13:02:22 INFO]: Allow Zombie Pigmen to spawn from portal blocks: false
[13:02:22 INFO]: Experience Merge Radius: 10.0
[13:02:22 INFO]: Zombie Aggressive Towards Villager: true
[13:02:22 INFO]: Nerfing mobs spawned from spawners: false
[13:02:23 INFO]: Preparing start region for level 0 (Seed: 27594263)
[13:02:23 INFO]: Preparing start region for level 1 (Seed: 27594263)
[13:02:23 INFO]: [CoreProtect] Enabling CoreProtect v2.14.4
[13:02:23 INFO]: [CoreProtect] CoreProtect has been successfully enabled!
[13:02:23 INFO]: [CoreProtect] Using SQLite for data storage.
[13:02:23 INFO]: [dynmap] Enabling dynmap v3.0-beta-3-160
[13:02:24 INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
[13:02:24 INFO]: [PermissionsEx] Initializing file backend
[13:02:24 INFO]: [PermissionsEx] Permissions file successfully reloaded
[13:02:24 INFO]: [Vault][Permission] PermissionsEx hooked.
[13:02:24 INFO]: [Vault][Chat] PermissionsEx_Chat hooked.
[13:02:24 INFO]: [dynmap] Using PermissionsEx 1.23.4 for access control
[13:02:24 INFO]: [dynmap] Mod Support processing completed
[13:02:24 INFO]: [dynmap] Loaded 26 shaders.
[13:02:24 INFO]: [dynmap] Loaded 82 perspectives.
[13:02:24 INFO]: [dynmap] Loaded 14 lightings.
[13:02:24 INFO]: [dynmap] Web server started on address 0.0.0.0:25570
[13:02:24 INFO]: [dynmap] version 3.0-beta-3-160 is enabled - core version 3.0-beta-3-160
[13:02:24 INFO]: [dynmap] For support, visit https://forums.dynmap.us
[13:02:24 INFO]: [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
[13:02:24 INFO]: [dynmap] Loaded 1 maps of world 'GKD'.
[13:02:24 INFO]: [dynmap] World 'GKD_nether' disabled
[13:02:24 INFO]: [dynmap] Enabled
[13:02:24 INFO]: [BlockParticles] Enabling BlockParticles v1.9.7.2
[13:02:24 INFO]: [PluginConstructorAPI] Enabling PluginConstructorAPI v1.0.51
[13:02:24 INFO]: [OpenInv] Enabling OpenInv v3.3.5
[13:02:24 INFO]: [Essentials] Enabling Essentials vTeamCity
[13:02:24 WARN]: [Essentials] Ignoring attempt to change parent of plugin logger
[13:02:24 INFO]: [Essentials] Using locale en
[13:02:24 INFO]: [Essentials] Using locale en
[13:02:24 INFO]: [Vault][Economy] Essentials Economy hooked.
[13:02:24 INFO]: [Essentials] Essentials: Using PermissionsEx based permissions.
[13:02:24 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.9.2
[13:02:24 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[13:02:24 INFO]: [PlaceholderAPI] Fetching available expansion information...
[13:02:24 INFO]: [PlugMan] Enabling PlugMan v2.1.6
[13:02:24 INFO]: [ConsoleScheduler] Enabling ConsoleScheduler v1.4.8
[13:02:24 INFO]: [ConsoleScheduler] Vault Found! Hooking as permission system
[13:02:24 INFO]: [ConsoleScheduler] By BoomerBR & Boomclaw - v1.4.8 enabled.
[13:02:24 INFO]: [ConsoleScheduler] Command execution will start in 5 seconds.
[13:02:24 INFO]: [WorldBorder] Enabling WorldBorder v1.8.7
[13:02:24 INFO]: [WorldBorder] [CONFIG] Using rectangular/square border, knockback of 3.0 blocks, and timer delay of 5.
[13:02:24 INFO]: [WorldBorder] [CONFIG] Border-checking timed task started.
[13:02:24 INFO]: [WorldBorder] [CONFIG] World "GKD" has border radius 7100 at X: 0.5 Z: 0.5
[13:02:24 INFO]: [WorldBorder] [CONFIG] Successfully hooked into DynMap for the ability to display borders.
[13:02:24 INFO]: [WorldBorder] For reference, the main world's spawn location is at X: 0.0 Y: 46.0 Z: -1.0
[13:02:24 INFO]: [BetterChairs] Enabling BetterChairs v0.9.5
[13:02:24 INFO]: [BetterChairs] Your server is running version v1_12_R1
[13:02:24 INFO]: [BetterChairs] NMS hooked !
[13:02:24 INFO]: [EasyBackup] Enabling EasyBackup v2.8.5
[13:02:24 INFO]: [EasyBackup] ----------------------------------------
[13:02:24 INFO]: [EasyBackup] Loading...
[13:02:24 INFO]: [EasyBackup] ----------------------------------------
[13:02:24 INFO]: [EasyBackup] Loading EasyBackup schedule.
[13:02:24 INFO]: [EasyBackup] Schedule applied: Mon Wed Fri 7:00 - data: 420
[13:02:24 INFO]: [EasyBackup] Schedule applied: 4:00 AM - data: 240
[13:02:24 INFO]: [EasyBackup] ----------------------------------------
[13:02:24 INFO]: [EasyBackup] Plugin has been loaded successfully
[13:02:24 INFO]: [EasyBackup] ----------------------------------------
[13:02:24 INFO]: [Votifier] Enabling Votifier v2.5.0
[13:02:24 INFO]: [Votifier] Loaded token for website: default
[13:02:24 INFO]: [Votifier] DEBUG mode enabled!
[13:02:24 INFO]: [Votifier] Method none selected for vote forwarding: Votes will not be received from a forwarder.
[13:02:24 ERROR]: [Votifier] Votifier was not able to bind to {}
[13:02:24 INFO]: [AntiWDL] Enabling AntiWDL v0.1
[13:02:24 INFO]: [AntiWDL] -----------------------------
[13:02:24 INFO]: [AntiWDL] Loading AntiWDL by Upd4ting
[13:02:24 INFO]: [AntiWDL] Check out my twitter: twitter.com/upd4ting
[13:02:24 INFO]: [AntiWDL] -----------------------------
[13:02:24 INFO]: [KitAdder] Enabling KitAdder v3
[13:02:24 INFO]: [KitAdder] KitAdder plugin has been enabled!
[13:02:24 INFO]: [VotingPlugin] Enabling VotingPlugin v5.13.6
[13:02:24 INFO]: [EasyBackup] ----------------------------------------
[13:02:24 INFO]: [EasyBackup] A new version of EasyBackup is available!
[13:02:24 INFO]: [EasyBackup] Current: 2.8.5, New: 2.9.0.2
[13:02:24 INFO]: [EasyBackup] Download it here: https://spigotmc.org/resources/8017
[13:02:24 INFO]: [EasyBackup] ----------------------------------------
[13:02:24 INFO]: [VotingPlugin] Enabled VotingPlugin 5.13.6
[13:02:24 WARN]: [VotingPlugin] No vote has been recieved from serverpact.nl, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[13:02:24 INFO]: [OldCombatMechanics] Enabling OldCombatMechanics v1.6.6
[13:02:24 INFO]: Registering hook...
[13:02:25 INFO]: [OldCombatMechanics] OldCombatMechanics v1.6.6 has been enabled
[13:02:25 INFO]: [EssentialsAntiBuild] Enabling EssentialsAntiBuild vTeamCity
[13:02:25 INFO]: [MaintenanceSpigot] Enabling MaintenanceSpigot v3.0.1
[13:02:25 INFO]: [MaintenanceSpigot] Plugin by KennyTV
[13:02:25 INFO]: [WooMinecraft] Enabling WooMinecraft v1.1.2-S1.12.1-R0.1
[13:02:25 INFO]: [WooMinecraft] Commando's Geïnitialiseerd
[13:02:25 INFO]: [WooMinecraft] Donatie systeem geactiveerd!
[13:02:25 INFO]: [StaffPlus] Enabling StaffPlus v3.2.8.2
[13:02:25 INFO]: [APIManager] API class 'org.inventivetalent.packetlistener.PacketListenerAPI' is not yet initialized. Creating new instance.
[13:02:25 INFO]: [ReflectionHelper] Version is v1_12_R1 (11201)
[13:02:25 INFO]: [PacketListenerAPI] Using INChannel
[13:02:25 WARN]: java.lang.NoSuchFieldException: list
[13:02:25 WARN]: at java.lang.Class.getDeclaredField(Class.java:2070)
[13:02:25 WARN]: at org.inventivetalent.packetlistener.channel.ChannelAbstract.addServerChannel(ChannelAbstract.java:69)
[13:02:25 WARN]: at org.inventivetalent.packetlistener.ChannelInjector.addServerChannel(ChannelInjector.java:55)
[13:02:25 WARN]: at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:32)
[13:02:25 WARN]: at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:46)
[13:02:25 WARN]: at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:117)
[13:02:25 WARN]: at net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:105)
[13:02:25 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:02:25 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[13:02:25 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:02:25 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[13:02:25 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[13:02:25 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[13:02:25 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[13:02:25 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[13:02:25 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[13:02:25 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[13:02:25 WARN]: at java.lang.Thread.run(Thread.java:748)
[13:02:25 INFO]: [PacketListenerAPI] Injected custom channel handlers.
[13:02:25 INFO]: [PacketListenerAPI] Adding channels for online players...
[13:02:25 INFO]: [Staff+] Version protocol set to 'v1_12_R1'.
[13:02:25 INFO]: [Staff+] Staff+ has been enabled! Initialization took 51ms.
[13:02:25 INFO]: [Staff+] Plugin created by Shortninja.
[13:02:25 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn vTeamCity
[13:02:25 INFO]: [PlayerParticles] Enabling PlayerParticles v6.4
[13:02:25 INFO]: [ItemRestrict] Enabling ItemRestrict v2.4.1
[13:02:25 INFO]: [ItemRestrict] Server version detected: 1.12.2
[13:02:25 INFO]: [ItemRestrict] Loading the config file...
[13:02:25 INFO]: [ItemRestrict] Restrictions enabled on all worlds.
[13:02:25 WARN]: [ItemRestrict] Removing recipes from the game is not possible in 1.12 due to a spigot bug: https://goo.gl/4v71Zv .Use CraftingBanned feature until this is fixed!
[13:02:25 INFO]: [ItemRestrict] Brewing restrictions enabled!
[13:02:25 INFO]: [ItemRestrict] Wearing restrictions enabled!
[13:02:25 INFO]: [ItemRestrict] Creative restrictions enabled!
[13:02:25 INFO]: [ItemRestrict] Pickup restrictions enabled!
[13:02:25 INFO]: [ItemRestrict] Drop restrictions enabled!
[13:02:25 INFO]: [ItemRestrict] Block break restrictions enabled!
[13:02:25 INFO]: [ItemRestrict] WorldScanner is disabled!
[13:02:25 INFO]: [ItemRestrict] ItemRestrict loaded successfully!
[13:02:25 INFO]: [LiteBans] Enabling LiteBans v2.3.15
[13:02:25 INFO]: [LiteBans] Using default database drivers.
[13:02:25 INFO]: [LiteBans] Loading SQL driver: h2 (org.h2.Driver)
[13:02:25 INFO]: [LiteBans] Connecting to database...
[13:02:25 INFO]: [LiteBans] Connected to [jdbc:h2:///home/container/plugins/LiteBans/litebans] (121 ms).
[13:02:25 INFO]: [LiteBans] Database connection fully initialized (123.8 ms).
[13:02:25 INFO]: [LiteBans] v2.3.15 enabled. Startup took 250 ms.
[13:02:25 INFO]: [VoxelSniper] Enabling VoxelSniper v5.172.0-SNAPSHOT
[13:02:25 INFO]: [VoxelSniper] Registered 75 Sniper Brushes with 149 handles.
[13:02:25 INFO]: [VoxelSniper] Registered Sniper Listener.
[13:02:25 INFO]: [MineSync] Enabling MineSync vS_2.1.0
[13:02:25 INFO]: [WorldEdit] Enabling WorldEdit v6.1.7;dd00bb1
[13:02:25 INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[13:02:25 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R1 as the Bukkit adapter
[13:02:25 INFO]: [WorldGuard] Enabling WorldGuard v6.2.2-SNAPSHOT;8eeab68
[13:02:25 INFO]: [WorldGuard] (GKD) TNT ignition is PERMITTED.
[13:02:25 INFO]: [WorldGuard] (GKD) Lighters are PERMITTED.
[13:02:25 INFO]: [WorldGuard] (GKD) Lava fire is blocked.
[13:02:25 INFO]: [WorldGuard] (GKD) All fire spread is disabled.
[13:02:25 INFO]: [WorldGuard] Loaded configuration for world 'GKD'
[13:02:25 INFO]: [WorldGuard] (GKD_nether) TNT ignition is PERMITTED.
[13:02:25 INFO]: [WorldGuard] (GKD_nether) Lighters are PERMITTED.
[13:02:25 INFO]: [WorldGuard] (GKD_nether) Lava fire is blocked.
[13:02:25 INFO]: [WorldGuard] (GKD_nether) All fire spread is disabled.
[13:02:25 INFO]: [WorldGuard] Loaded configuration for world 'GKD_nether'
[13:02:25 INFO]: [WorldGuard] Loading region data...
[13:02:27 INFO]: [CombatLogX] Enabling CombatLogX v9.6.0.2
[13:02:27 INFO]: [OpenAudioMc] Enabling OpenAudioMc v5.2
[13:02:27 WARN]: [OpenAudioMc] Could not save data.yml to plugins/OpenAudioMc/data.yml because data.yml already exists.
[13:02:27 INFO]: [OpenAudioMc-Log] Starting configuration module
[13:02:27 INFO]: [OpenAudioMc-Log] Starting authentication module
[13:02:27 INFO]: [OpenAudioMc-Log] Enabling the 1.12 speaker system
[13:02:27 INFO]: [OpenAudioMc-Log] Hooking speakers attempt 1..
[13:02:27 INFO]: [OpenAudioMc-Log] Hooking speakers attempt 2..
[13:02:27 INFO]: [OpenAudioMc-Log] Failed hook speakers attempt 2..
[13:02:27 INFO]: [OpenAudioMc-Log] Turns out you have WorldGuard installed! enabling regions and the region tasks..
[13:02:27 INFO]: [OpenAudioMc-Log] Unknown version. Falling back to the 1.8 to 1.12 region implementation.
[13:02:27 INFO]: [Dynmap-WorldGuard] Enabling Dynmap-WorldGuard v0.90
[13:02:27 INFO]: [Dynmap-WorldGuard] initializing
[13:02:27 INFO]: [Dynmap-WorldGuard] Custom flag 'dynmap-boost' not registered - WGCustomFlags not found
[13:02:27 INFO]: [Dynmap-WorldGuard] version 0.90 is activated
[13:02:27 INFO]: Done (5.105s)! For help, type "help" or "?"
[Pterodactyl Daemon] Server marked as ON
[13:02:27 INFO]: Starting GS4 status listener
[13:02:27 INFO]: Query running on 0.0.0.0:25565
[13:02:27 INFO]: Timings Reset
[13:02:28 INFO]: (FAWE) Plugin 'WorldGuard' found. Using it now.
[13:02:28 INFO]: [GKD] Enabling expansion 'Notifier v13.9'
[13:02:28 INFO]: [GKD] Successfully enabled 1 expansions
[13:02:28 INFO]: [VotingPlugin] Hooked into Vault permissions
[13:02:28 INFO]: [ConsoleScheduler] has started executing commands
[13:02:28 INFO]: -------------[ConsoleScheduler]--------------
[13:02:28 INFO]: getConfig contains CommandSchedule.Command1
[13:02:28 INFO]: [ConsoleScheduler] has attempted to put 1 commands on schedule.
[13:02:28 INFO]: [VotingPlugin] Successfully hooked into Vault!
[13:02:28 INFO]: [VotingPlugin] VotingPlugin has an update available! Your Version: 5.13.6 New Version: 5.18.3 Use /av download to get the latest update!
[13:02:29 WARN]: [VotingPlugin] Detected an issue with voting sites, check the plugin startup log for more details
[13:02:29 INFO]: [PlaceholderAPI] 131 placeholder expansions are available on the cloud.
[13:02:33 INFO]: Saving...
[13:02:33 INFO]: Saved the world

**This is all i have for you, please ignore other plugins, we are still trying to fix a few things here.**

**Comment by Valtorian** [comment]
Why don't you make a Discord? Thats way more easy to communicate :p

**Comment by Qballl** [comment]
I actually do have one https://discord.gg/N6VqtYC
