### ISSUE TITLE
Console startup log

### ISSUE THREAD

**Issue by Dysnomia2005** [Qballl/StaffPlus#73]
[17:43:50] [Server thread/INFO]: [Staff+] Version protocol set to 'v1_14_R1'.
[17:43:50] [Server thread/INFO]: ninePlus is: true
[17:43:50] [Server thread/INFO]: twelvePlus is: true
[17:43:50] [Server thread/ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 15, column 1:
    general-prefix: "&dStaff+ &8┬╗"
    ^
expected <block end>, but found '<scalar>'
 in 'string', line 75, column 21:
    disabled: "disabled"'
                        ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:212) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.shortninja.staffplus.server.data.file.LanguageFile.copyFile(LanguageFile.java:54) [Staff+.jar:?]
        at net.shortninja.staffplus.server.data.file.LanguageFile.<init>(LanguageFile.java:24) [Staff+.jar:?]
        at net.shortninja.staffplus.StaffPlus.start(StaffPlus.java:153) [Staff+.jar:?]
        at net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:107) [Staff+.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 15, column 1:
    general-prefix: "&dStaff+ &8┬╗"
    ^
expected <block end>, but found '<scalar>'
 in 'string', line 75, column 21:
    disabled: "disabled"'
                        ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        ... 15 more
[17:43:50] [Server thread/INFO]: [Staff+] Creating language file 'lang_en'.
[17:43:50] [Server thread/INFO]: This should update lang file
[17:43:50] [Server thread/ERROR]: Error occurred while enabling StaffPlus v3.2.9 (Is it up to date?)
java.lang.NullPointerException: null
        at net.shortninja.staffplus.util.lib.JavaUtils.stringToList(JavaUtils.java:67) ~[?:?]
        at net.shortninja.staffplus.server.data.config.Messages.<init>(Messages.java:24) ~[?:?]
        at net.shortninja.staffplus.StaffPlus.start(StaffPlus.java:154) ~[?:?]
        at net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:107) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by Qballl** [comment]
Sorry was a bit busy simple fix on my end just posted an update on spigot
