### ISSUE TITLE
Generated an exception

### ISSUE THREAD

**Issue by Ant4rez** [Qballl/StaffPlus#8]
When i start the server this error appears, and still spaming the console.

```
[14:00:50] [Server thread/WARN]: [StaffPlus] Task #34 for StaffPlus v3.2.3 generated an exception
java.lang.NullPointerException: null
	at net.shortninja.staffplus.player.UserManager.getAll(UserManager.java:22) ~[?:?]
	at net.shortninja.staffplus.player.attribute.infraction.InfractionCoordinator.getWarnings(InfractionCoordinator.java:55) ~[?:?]
	at net.shortninja.staffplus.Tasks.checkWarnings(Tasks.java:56) ~[?:?]
	at net.shortninja.staffplus.Tasks.run(Tasks.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

And when you stop the server this appears:

`[14:01:05] [Server thread/ERROR]: Error occurred while disabling StaffPlus v3.2.3 (Is it up to date?)
java.lang.NullPointerException: null
	at net.shortninja.staffplus.player.UserManager.getAll(UserManager.java:22) ~[?:?]
	at net.shortninja.staffplus.StaffPlus.saveUsers(StaffPlus.java:140) ~[?:?]
	at net.shortninja.staffplus.StaffPlus.stop(StaffPlus.java:273) ~[?:?]
	at net.shortninja.staffplus.StaffPlus.onDisable(StaffPlus.java:125) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:350) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:613) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`

**Comment by Qballl** [comment]
Hmm I've gotten reports of this already I will look into this

**Comment by Qballl** [comment]
Im gonna close this as I believe it is fixed if not please feel free to open a new one.
